#############################################################
# Makefile for NANDErase program                            #
#############################################################
# Auth: Daniel Allred
#	    
PROGRAM:=NANDEraser

PROJECTFILE=$(PROGRAM).pjt
EXECUTABLE=./Debug/$(PROGRAM).out


# Target definitions
.PHONY : all clean
all: 
		timake $(PROJECTFILE) Debug

clean:
		timake $(PROJECTFILE) Debug -clean



