#! /bin/sh

matrixgui="/usr/bin/matrix_guiE"
PIDFILE="/var/run/matrix-gui-e.pid"

test -x "$matrixgui" || exit 0

default_display="`cat /sys/devices/platform/omapdss/manager0/display`"

case "$1" in
  start)
	if [ "$default_display" = "lcd" ]; then
    	export TSLIB_TSDEVICE=/dev/input/touchscreen0
    	export QWS_MOUSE_PROTO=Tslib:/dev/input/touchscreen0
    	if [ ! -f /etc/pointercal ] ; then
        	echo -n "Calibrating touchscreen (first time only)"
        	ts_calibrate
        	echo "."
    	fi
	    rotation="90"
	else
		rotation="0"
	fi
	
	GUI_OPTS="-qws -display transformed:Rot$rotation /usr/share/matrix/html/menu_main_1.html"
	if [ -e $PIDFILE ]; then
      PIDDIR=/proc/$(cat $PIDFILE)
      if [ -d ${PIDDIR} -a  "$(readlink -f ${PIDDIR}/exe)" = "${matrixgui}" ]; then
        echo "$DESC already started; not starting."
      else
        echo "Removing stale PID file $PIDFILE."
        rm -f $PIDFILE
      fi
    fi

    echo -n "Starting Matrix GUI application"
    start-stop-daemon --start --quiet --background --exec $matrixgui -- $GUI_OPTS
	pidof matrix_guiE > $PIDFILE
    echo "."
    ;;

  stop)
    echo -n "Stopping Matrix GUI application"
    start-stop-daemon --stop --quiet --pidfile /var/run/matrix-gui-e.pid
    echo "."
    ;;
  *)
    echo "Usage: /etc/init.d/matrix-gui-e {start|stop}"
    exit 1
esac

exit 0
