#! /bin/sh

matrixgui="/usr/bin/matrix_gui"
GUI_OPTS="-qws -display transformed:Rot0 /usr/share/matrix/html/menu_main.html"
PIDFILE="/var/run/matrix-gui.pid"

test -x "$matrixgui" || exit 0
export TSLIB_TSDEVICE=/dev/input/touchscreen0
export QWS_MOUSE_PROTO=Tslib:/dev/input/touchscreen0

case "$1" in
  start)
    if [ ! -f /etc/pointercal ] ; then
        echo -n "Calibrating touchscreen (first time only)"
        ts_calibrate
        echo "."
    fi

    chvt 4
    if [ -e $PIDFILE ]; then
      PIDDIR=/proc/$(cat $PIDFILE)
      if [ -d ${PIDDIR} -a  "$(readlink -f ${PIDDIR}/exe)" = "${matrixgui}" ]; then
        echo "$DESC already started; not starting."
      else
        echo "Removing stale PID file $PIDFILE."
        rm -f $PIDFILE
      fi
    fi
    echo -n "Starting Matrix GUI application"
    echo LCD > /sys/class/davinci_display/ch0/output
    echo 480x272 > /sys/class/davinci_display/ch0/mode
    start-stop-daemon --start --quiet --background --pidfile /var/run/matrix-gui.pid --exec $matrixgui -- $GUI_OPTS
    echo "."
	pidof matrix_gui > $PIDFILE
    ;;
  stop)
    echo -n "Stopping Matrix GUI application"
    start-stop-daemon --stop --quiet --pidfile /var/run/matrix-gui.pid
    echo "."
    ;;
  *)
    echo "Usage: /etc/init.d/matrix-gui {start|stop}"
    exit 1
esac

exit 0
