/* this file was generated by linkcmd.xdt from the gnu.targets package */

/* function aliases */

/* input libraries */
INPUT(
    "/db/swcoe_asp/DM360/Kaleido/dm360/mpeg4_decoder/Client/Test/Src/mp4vdecTestApp/package/cfg/mp4vdecTestApp_x470MV.o470MV"
    "/db/swcoe_asp/DM360_Codecs/framework_components_2_23_00_03/packages/ti/sdo/fc/ires/edma3chan/lib/release/edma3Chan.a470MV"
    "/db/swcoe_asp/DM360_Codecs/framework_components_2_23_00_03/packages/ti/sdo/fc/edma3/lib/release/edma3.a470MV"
    "/db/swcoe_asp/DM360_Codecs/framework_components_2_23_00_03/packages/ti/sdo/fc/rman/lib/release/rman.a470MV"
    "/db/swcoe_asp/DM360_Codecs/framework_components_2_23_00_03/packages/ti/sdo/fc/ires/nullresource/lib/release/nullres.a470MV"
    "/db/swcoe_asp/DM360_Codecs/framework_components_2_23_00_03/packages/ti/sdo/fc/utils/api/lib/release/api.a470MV"
    "/db/swcoe_asp/DM360_Codecs/framework_components_2_23_00_03/packages/ti/sdo/fc/ires/addrspace/lib/release/addrspace.a470MV"
    "/db/swcoe_asp/DM360_Codecs/framework_components_2_23_00_03/examples/ti/sdo/fc/rman/examples/lib/release/rmanExample.a470MV"
    "/db/swcoe_asp/DM360_Codecs/framework_components_2_23_00_03/packages/ti/sdo/fc/ires/vicp/lib/release/vicp.a470MV"
    "/db/swcoe_asp/DM360_Codecs/framework_components_2_23_00_03/packages/ti/sdo/fc/utils/lib/release/rmm.a470MV"
    "/db/swcoe_asp/DM360_Codecs/framework_components_2_23_00_03/packages/ti/sdo/fc/utils/lib/release/smgr.a470MV"
    "/db/swcoe_asp/DM360_Codecs/framework_components_2_23_00_03/packages/ti/sdo/fc/utils/lib/release/rmmp.a470MV"
    "/db/swcoe_asp/DM360_Codecs/framework_components_2_23_00_03/packages/ti/sdo/fc/utils/lib/release/smgrmp.a470MV"
    "/db/swcoe_asp/DM360_Codecs/framework_components_2_23_00_03/packages/ti/sdo/fc/utils/lib/release/shm.a470MV"
    "/db/swcoe_asp/DM360_Codecs/framework_components_2_23_00_03/packages/ti/sdo/fc/memutils/lib/release/memutils.a470MV"
    "/db/swcoe_asp/DM360_Codecs/framework_components_2_23_00_03/packages/ti/sdo/fc/vicpsync/lib/release/vicpsync.a470MV"
    "/db/swcoe_asp/DM360_Codecs/framework_components_2_23_00_03/packages/ti/sdo/fc/utils/gtinfra/lib/release/gt_noOs.a470MV"
    "/db/swcoe_asp/DM360_Codecs/framework_components_2_23_00_03/fctools/packages/ti/sdo/linuxutils/edma/lib/edma.a470MV"
    "/db/swcoe_asp/DM360_Codecs/framework_components_2_23_00_03/fctools/packages/ti/sdo/linuxutils/vicp/lib/vicp.a470MV"
    "/db/swcoe_asp/DM360_Codecs/framework_components_2_23_00_03/fctools/packages/ti/sdo/linuxutils/cmem/lib/cmem.a470MV"
    "/db/swcoe_asp/DM360_Codecs/framework_components_2_23_00_03/packages/ti/sdo/utils/trace/lib/release/gt.a470MV"
    "/db/swcoe_asp/DM360_Codecs/xdctools_3_15_00_10/packages/gnu/targets/rts470MV/lib/gnu.targets.rts470MV.a470MV"
)
