# 
#  Copyright (c) 2010, Texas Instruments Incorporated
#  All rights reserved.
# 
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions
#  are met:
# 
#  *  Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
# 
#  *  Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
# 
#  *  Neither the name of Texas Instruments Incorporated nor the names of
#     its contributors may be used to endorse or promote products derived
#     from this software without specific prior written permission.
# 
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
#  THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
#  PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR
#  CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
#  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE,
#  EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
# 
#

#
#  ======== makefile ========
#

all:
%::
	$(MAKE) -C viddec1_copy $@
	$(MAKE) -C viddec2_copy $@
	$(MAKE) -C videnc1_copy $@
	$(MAKE) -C imgdec1_copy $@
	$(MAKE) -C imgenc1_copy $@
	$(MAKE) -C sphenc1_copy $@
	$(MAKE) -C sphdec1_copy $@
	$(MAKE) -C audenc1_copy $@
	$(MAKE) -C auddec1_copy $@
	$(MAKE) -C viddec_copy $@
	$(MAKE) -C videnc_copy $@
	$(MAKE) -C imgdec_copy $@
	$(MAKE) -C imgenc_copy $@
	$(MAKE) -C auddec_copy $@
	$(MAKE) -C audenc_copy $@
	$(MAKE) -C auddec1_ires $@
	$(MAKE) -C sphenc_copy $@
	$(MAKE) -C sphdec_copy $@
	$(MAKE) -C scale $@
	$(MAKE) -C g711 $@
	$(MAKE) -C vidtranscode_copy $@
	$(MAKE) -C vidanalytics_copy $@
	$(MAKE) -C viddec2split_copy $@
	$(MAKE) -C universal_copy $@
#
#  @(#) ti.sdo.ce.examples.codecs; 1, 0, 0,262; 12-2-2010 21:21:40; /db/atree/library/trees/ce/ce-r11x/src/ xlibrary

#

