#
#  Copyright 2010 by Texas Instruments Incorporated.
#  
#

#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
clean::
	-$(RM) -f *.pdb

unexport MAKEFILE_LIST
override PKGDIR = ti/sdo/ce/examples/apps/video_copy/dualcpu_separateconfig_dll
XDCINCS = -I. -I$(strip $(subst ;, -I,$(subst $(space),\$(space),$(XPKGPATH))))
XDCCFGDIR = package/cfg/

#
# The following dependencies ensure package.mak is rebuilt
# in the event that some included BOM script changes.
#
ifneq (clean,$(MAKECMDGOALS))
/db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/ti/targets/package/ti.targets.sch:
package.mak: /db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/ti/targets/package/ti.targets.sch
/db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/xdc/bld/BuildEnvironment.xs:
package.mak: /db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/xdc/bld/BuildEnvironment.xs
package.mak: package.bld
/db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/xdc/template.xs:
package.mak: /db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/xdc/template.xs
/db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/ti/targets/ITarget.xs:
package.mak: /db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/ti/targets/ITarget.xs
/db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/xdc/shelf/package/xdc.shelf.sch:
package.mak: /db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/xdc/shelf/package/xdc.shelf.sch
/db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/ti/targets/package.xs:
package.mak: /db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/ti/targets/package.xs
/db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/xdc/bld/Executable.xs:
package.mak: /db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/xdc/bld/Executable.xs
/db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/xdc/bld/PackageContents.xs:
package.mak: /db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/xdc/bld/PackageContents.xs
/db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/gnu/targets/MVArm9.xs:
package.mak: /db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/gnu/targets/MVArm9.xs
/db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/xdc/bld/Script.xs:
package.mak: /db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/xdc/bld/Script.xs
/db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/xdc/bld/ITargetFilter.xs:
package.mak: /db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/xdc/bld/ITargetFilter.xs
/db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/microsoft/targets/package/microsoft.targets.sch:
package.mak: /db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/microsoft/targets/package/microsoft.targets.sch
/db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/gnu/targets/UCArm9.xs:
package.mak: /db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/gnu/targets/UCArm9.xs
/db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/xdc/xdc.tci:
package.mak: /db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/xdc/xdc.tci
/db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/xdc/services/global/Clock.xs:
package.mak: /db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/xdc/services/global/Clock.xs
/db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/include/utils.tci:
package.mak: /db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/include/utils.tci
/db/atree/library/trees/ce/ce-n01x/src/config.bld:
package.mak: /db/atree/library/trees/ce/ce-n01x/src/config.bld
/db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/microsoft/targets/_utils.xs:
package.mak: /db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/microsoft/targets/_utils.xs
/db/atree/library/trees/ce/ce-n01x/src/user.bld:
package.mak: /db/atree/library/trees/ce/ce-n01x/src/user.bld
/db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/xdc/bld/Repository.xs:
package.mak: /db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/xdc/bld/Repository.xs
/db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/xdc/bld/package/xdc.bld.sch:
package.mak: /db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/xdc/bld/package/xdc.bld.sch
/db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/xdc/corevers/package/xdc.corevers.sch:
package.mak: /db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/xdc/corevers/package/xdc.corevers.sch
/db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/xdc/bld/_gen.xs:
package.mak: /db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/xdc/bld/_gen.xs
/db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/xdc/services/spec/package/xdc.services.spec.sch:
package.mak: /db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/xdc/services/spec/package/xdc.services.spec.sch
/db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/xdc/services/global/package/xdc.services.global.sch:
package.mak: /db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/xdc/services/global/package/xdc.services.global.sch
/db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/xdc/services/intern/cmd/package/xdc.services.intern.cmd.sch:
package.mak: /db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/xdc/services/intern/cmd/package/xdc.services.intern.cmd.sch
/db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/xdc/package.xs:
package.mak: /db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/xdc/package.xs
/db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/gnu/targets/Linux86.xs:
package.mak: /db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/gnu/targets/Linux86.xs
/db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/xdc/xmlgen.xs:
package.mak: /db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/xdc/xmlgen.xs
/db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/microsoft/targets/ITarget.xs:
package.mak: /db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/microsoft/targets/ITarget.xs
/db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/gnu/targets/arm/package/gnu.targets.arm.sch:
package.mak: /db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/gnu/targets/arm/package/gnu.targets.arm.sch
/db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/microsoft/targets/package.xs:
package.mak: /db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/microsoft/targets/package.xs
/db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/xdc/package/xdc.sch:
package.mak: /db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/xdc/package/xdc.sch
/db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/microsoft/targets/Win32.xs:
package.mak: /db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/microsoft/targets/Win32.xs
/db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/xdc/bld/Library.xs:
package.mak: /db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/xdc/bld/Library.xs
/db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/gnu/targets/package/gnu.targets.sch:
package.mak: /db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/gnu/targets/package/gnu.targets.sch
/db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/xdc/bld/ITarget.xs:
package.mak: /db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/xdc/bld/ITarget.xs
/db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/xdc/IPackage.xs:
package.mak: /db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/xdc/IPackage.xs
/db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/xdc/bld/Utils.xs:
package.mak: /db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/xdc/bld/Utils.xs
/db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/xdc/services/intern/xsr/package/xdc.services.intern.xsr.sch:
package.mak: /db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/xdc/services/intern/xsr/package/xdc.services.intern.xsr.sch
/db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/gnu/targets/arm/GCArmv7A.xs:
package.mak: /db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/gnu/targets/arm/GCArmv7A.xs
/db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/xdc/services/intern/gen/package/xdc.services.intern.gen.sch:
package.mak: /db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/xdc/services/intern/gen/package/xdc.services.intern.gen.sch
/db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/xdc/bld/package.xs:
package.mak: /db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/xdc/bld/package.xs
/db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/microsoft/targets/arm/package/microsoft.targets.arm.sch:
package.mak: /db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/microsoft/targets/arm/package/microsoft.targets.arm.sch
/db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/xdc/om2.xs:
package.mak: /db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/xdc/om2.xs
/db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/gnu/targets/Mingw.xs:
package.mak: /db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/gnu/targets/Mingw.xs
/db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/gnu/targets/ITarget.xs:
package.mak: /db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/gnu/targets/ITarget.xs
/db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/gnu/targets/package.xs:
package.mak: /db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/gnu/targets/package.xs
/db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/xdc/xmlgen2.xs:
package.mak: /db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/xdc/xmlgen2.xs
/db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/xdc/recap.xs:
package.mak: /db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/xdc/recap.xs
/db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/gnu/targets/arm/GCArmv6.xs:
package.mak: /db/rtree/install/trees/products/xdcprod-j59/product/Linux/xdctools_3_10_04/packages/gnu/targets/arm/GCArmv6.xs
endif

all,64P .libraries,64P .dlls,64P .executables,64P test,64P:;
all,674 .libraries,674 .dlls,674 .executables,674 test,674:;
all,86U .libraries,86U .dlls,86U .executables,86U test,86U:;
all,v5T .libraries,v5T .dlls,v5T .executables,v5T test,v5T:;
all,v4TCE .libraries,v4TCE .dlls,v4TCE .executables,v4TCE test,v4TCE:;
all,470uC .libraries,470uC .dlls,470uC .executables,470uC test,470uC:;

all: .executables 
.executables: .libraries .dlls
.libraries: .interfaces

PKGCFGS := $(wildcard package.xs) package/build.cfg
.interfaces: package/package.xdc.inc package/package.defs.h package.xdc $(PKGCFGS)

-include package/package.xdc.dep
package/%.xdc.inc package/%_ti.sdo.ce.examples.apps.video_copy.dualcpu_separateconfig_dll.c package/%.defs.h: %.xdc $(PKGCFGS)
	@$(MSG) generating interfaces for package ti.sdo.ce.examples.apps.video_copy.dualcpu_separateconfig_dll" (because $@ is older than $(firstword $?))" ...
	$(XSRUN) -f xdc/services/intern/cmd/build.xs $(MK_IDLOPTS) -m package/package.xdc.dep -i package/package.xdc.inc package.xdc

ifneq (clean,$(MAKECMDGOALS))
-include package/package.cfg.dep
endif

package/package.ext.xml: package/package.cfg.xdc.inc
package/package.cfg.xdc.inc: $(XDCROOT)/packages/xdc/cfg/cfginc.js package.xdc
	@$(MSG) generating schema include file list ...
	$(CONFIG) -f $(XDCROOT)/packages/xdc/cfg/cfginc.js ti.sdo.ce.examples.apps.video_copy.dualcpu_separateconfig_dll $@

test:;
%,copy:
	@$(if $<,,$(MSG) don\'t know how to build $*; exit 1)
	@$(MSG) cp $< $@
	$(RM) $@
	$(CP) $< $@

$(XDCCFGDIR)%.c $(XDCCFGDIR)%.h $(XDCCFGDIR)%.xdl: $(XDCCFGDIR)%.cfg .interfaces $(XDCROOT)/packages/xdc/cfg/Main.xs
	@$(MSG) "configuring $(_PROG_NAME) from $< ..."
	$(CONFIG) $(_PROG_XSOPTS) xdc.cfg $(_PROG_NAME) $(XDCCFGDIR)$*.cfg $(XDCCFGDIR)$*

.PHONY: release,ti_sdo_ce_examples_apps_video_copy_dualcpu_separateconfig_dll
ti_sdo_ce_examples_apps_video_copy_dualcpu_separateconfig_dll.tar: package/build.cfg
ti_sdo_ce_examples_apps_video_copy_dualcpu_separateconfig_dll.tar: package/package.cfg.xdc.inc
ti_sdo_ce_examples_apps_video_copy_dualcpu_separateconfig_dll.tar: package/package.ext.xml
ti_sdo_ce_examples_apps_video_copy_dualcpu_separateconfig_dll.tar: package/package.xdc.inc
ti_sdo_ce_examples_apps_video_copy_dualcpu_separateconfig_dll.tar: package/package.bld.xml
ti_sdo_ce_examples_apps_video_copy_dualcpu_separateconfig_dll.tar: package/package.rel.dot
ifneq (clean,$(MAKECMDGOALS))
-include package/rel/ti_sdo_ce_examples_apps_video_copy_dualcpu_separateconfig_dll.tar.dep
-include package/rel/ti_sdo_ce_examples_apps_video_copy_dualcpu_separateconfig_dll.tar.rcl.dep
endif
package/rel/ti_sdo_ce_examples_apps_video_copy_dualcpu_separateconfig_dll/ti/sdo/ce/examples/apps/video_copy/dualcpu_separateconfig_dll/package/package.rel.xml:

ti_sdo_ce_examples_apps_video_copy_dualcpu_separateconfig_dll.tar: package/rel/ti_sdo_ce_examples_apps_video_copy_dualcpu_separateconfig_dll.xdc.inc package/rel/ti_sdo_ce_examples_apps_video_copy_dualcpu_separateconfig_dll/ti/sdo/ce/examples/apps/video_copy/dualcpu_separateconfig_dll/package/package.rel.xml
	@$(MSG) making release file $@ "(because of $(firstword $?))" ...
	-$(RM) $@
	$(call MKRELTAR,package/rel/ti_sdo_ce_examples_apps_video_copy_dualcpu_separateconfig_dll.xdc.inc,package/rel/ti_sdo_ce_examples_apps_video_copy_dualcpu_separateconfig_dll.tar.dep, tisb/release/filters/copyright.rel)


release release,ti_sdo_ce_examples_apps_video_copy_dualcpu_separateconfig_dll: all ti_sdo_ce_examples_apps_video_copy_dualcpu_separateconfig_dll.tar
clean:: .clean
	-$(RM) ti_sdo_ce_examples_apps_video_copy_dualcpu_separateconfig_dll.tar
	-$(RM) package/rel/ti_sdo_ce_examples_apps_video_copy_dualcpu_separateconfig_dll.xdc.inc
	-$(RM) package/rel/ti_sdo_ce_examples_apps_video_copy_dualcpu_separateconfig_dll.tar.dep

clean:: .clean
	-$(RM) .libraries .libraries,*
clean:: 
	-$(RM) .dlls .dlls,*
#
# The following clean rule removes user specified
# generated files or directories.
#

ifneq (clean,$(MAKECMDGOALS))
ifeq (,$(wildcard package))
    $(shell $(MKDIR) package)
endif
ifeq (,$(wildcard package/external))
    $(shell $(MKDIR) package/external)
endif
ifeq (,$(wildcard package/lib))
    $(shell $(MKDIR) package/lib)
endif
ifeq (,$(wildcard package/rel))
    $(shell $(MKDIR) package/rel)
endif
ifeq (,$(wildcard package/cfg))
    $(shell $(MKDIR) package/cfg)
endif
ifeq (,$(wildcard package/internal))
    $(shell $(MKDIR) package/internal)
endif
endif
clean::
	-$(RMDIR) package


#
#  @(#) ti.sdo.ce.examples.apps.video_copy; 1, 0, 0,77; 12-2-2010 21:21:32; /db/atree/library/trees/ce/ce-r11x/src/ xlibrary

#

