/*
 * dvtbParam.c
 *
 * DVTB Handlers Initialization
 *
 * Copyright (C) 2010 Texas Instruments Incorporated - http://www.ti.com/
 * 
 * 
 *  Redistribution and use in source and binary forms, with or without 
 *  modification, are permitted provided that the following conditions 
 *  are met:
 *
 *    Redistributions of source code must retain the above copyright 
 *    notice, this list of conditions and the following disclaimer.
 *
 *    Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in the 
 *    documentation and/or other materials provided with the   
 *    distribution.
 *
 *    Neither the name of Texas Instruments Incorporated nor the names of
 *    its contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS 
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT 
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 *  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT 
 *  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, 
 *  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT 
 *  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 *  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 *  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT 
 *  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE 
 *  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
*/

#include "dvtbParam.h"

DvevmStMapTable *MAP = NULL;
unsigned int DVEVM_CODEC_NUM = 0;

static DvevmStBool valInitialized = DVEVM_ST_FALSE;

/* Hack : C doesn't support non-constant initialization of global variables. We
 * achieve this in a round about way */

void
dvtb_initValues()
{
	if (!valInitialized)
	{
		/* className, fieldName, field Type, value, defaultValue */
		DvevmStMapTable dvevmStMapArr[] =
		{
		/* All global parameters */
		{ "engine", "name", DVEVM_ST_STR, G->eng.name, DEFAULT_ENGINE_NAME },

		/*V4L2 VPBE*/
		{ "vpbe", "device", DVEVM_ST_STR, G->vpbe.device, VID_DEVICE },
		{ "vpbe", "opMode", DVEVM_ST_INT, &(G->vpbe.opMode), (void *) DVEVM_ST_USERBUFFER },
		{ "vpbe", "standard", DVEVM_ST_INT, &(G->vpbe.dispStd), (void *) DVEVM_ST_720P_60 },
		{ "vpbe", "output", DVEVM_ST_INT, &(G->vpbe.dispOutput), (void *) DVEVM_ST_COMPONENT },
		{ "vpbe", "cropEnable", DVEVM_ST_INT, &(G->vpbe.cropEnable), (void *) DVEVM_ST_FALSE },
		{ "vpbe", "cropCapLeft", DVEVM_ST_INT, &(G->vpbe.crop.c.left), (void *) 0 },
		{ "vpbe", "cropCapTop", DVEVM_ST_INT, &(G->vpbe.crop.c.top), (void *) 0 },
		{ "vpbe", "cropCapWidth", DVEVM_ST_INT, &(G->vpbe.crop.c.width), (void *) NTSC_WIDTH },
		{ "vpbe", "cropCapHeight", DVEVM_ST_INT, &(G->vpbe.crop.c.height), (void *) NTSC_HEIGHT },

		/* Parameters for VPFE device */
		{ "vpfe", "device", DVEVM_ST_STR, G->vpfe.device, VIDCAP_DEVICE },
		{ "vpfe", "standard", DVEVM_ST_INT, &(G->vpfe.capStd), (void *) DVEVM_ST_720P_60 },
		{ "vpfe", "format", DVEVM_ST_INT, &(G->vpfe.capFmt), (void *) VID_FMT_YUV420SP },
		{ "vpfe", "input", DVEVM_ST_INT, &(G->vpfe.input), (void *) DVEVM_ST_COMPONENT },
		{ "vpfe", "width", DVEVM_ST_INT, &(G->vpfe.capWidth), (void *) NTSC_WIDTH },
		{ "vpfe", "height", DVEVM_ST_INT, &(G->vpfe.capHeight), (void *) NTSC_HEIGHT },
		{ "vpfe", "cropEnable", DVEVM_ST_INT, &(G->vpfe.cropEnable), (void *) DVEVM_ST_FALSE },
		{ "vpfe", "cropCapLeft", DVEVM_ST_INT, &(G->vpfe.crop.c.left), (void *) 0 },
		{ "vpfe", "cropCapTop", DVEVM_ST_INT, &(G->vpfe.crop.c.top), (void *) 0 },
		{ "vpfe", "cropCapWidth", DVEVM_ST_INT, &(G->vpfe.crop.c.width), (void *) NTSC_WIDTH },
		{ "vpfe", "cropCapHeight", DVEVM_ST_INT, &(G->vpfe.crop.c.height), (void *) NTSC_HEIGHT },
		{ "vpfe", "hdCaptureFactor", DVEVM_ST_INT, &(G->vpfe.hdCaptureFactor), (void *) 1 },

		/* Parameters for ALSA audio device */
		{ "audio", "device", DVEVM_ST_STR, G->aud.device, DEF_SND_DEVICE },
		{ "audio", "format", DVEVM_ST_INT, &(G->aud.format), (void *) SND_PCM_FORMAT_S16_LE },
		{ "audio", "samplerate", DVEVM_ST_INT, &(G->aud.sampleRate), (void *) DEF_SAMPLE_RATE },
		{ "audio", "channels", DVEVM_ST_INT, &(G->aud.numChannels), (void *) DEF_NUM_CHANNELS },
		{ "audio", "type", DVEVM_ST_INT, &(G->aud.blocking_mode), 0 },

		/* Parameters for Speech Decoder */
//		{"sphdec", "codec", DVEVM_ST_STR, G->sdec.sdecName, "g711dec"},
//		{"sphdec", "dataEnable", DVEVM_ST_INT, &(G->sdec.sdecParams.dataEnable), (void *) SPHDEC_DE },
//		{"sphdec", "compandingLaw", DVEVM_ST_INT,&(G->sdec.sdecParams.compandingLaw), (void *) SPHDEC_CL },
//		{"sphdec", "packingType", DVEVM_ST_INT, &(G->sdec.sdecParams.packingType), (void *) SPHDEC_PT },
//		{"sphdec", "inbufsize", DVEVM_ST_INT, &(G->sdec.inBuf.size), (void *) SPHDEC_INBUF_SIZE},
//		{"sphdec", "outbufsize", DVEVM_ST_INT, &(G->sdec.outBuf.size), (void *) SPHDEC_OUTBUF_SIZE},
		
		/* Parameters for Speech Encoder */
//		{"sphenc", "codec", DVEVM_ST_STR, G->senc.sencName, "g711enc"},
//		{"sphenc", "seconds", DVEVM_ST_INT, &(G->senc.seconds), (void *) DEFAULT_SPHENC_TIME},
//		{"sphenc", "frameSize", DVEVM_ST_INT,&(G->senc.sencParams.frameSize), (void *) SPHENC_FRAME_SIZE },
//		{"sphenc", "compandingLaw", DVEVM_ST_INT, &(G->senc.sencParams.compandingLaw), (void *) SPHENC_CL },
//		{"sphenc", "packingType", DVEVM_ST_INT, &(G->senc.sencParams.packingType), (void *) SPHENC_PT},
//		{"sphenc", "vadSelection", DVEVM_ST_INT, &(G->senc.sencParams.vadSelection),(void *) SPHENC_VS},
//		{"sphenc", "inbufsize", DVEVM_ST_INT, &(G->senc.inBuf.size), (void *) (SPHENC_FRAME_SIZE*2)},
//		{"sphenc", "outbufsize", DVEVM_ST_INT, &(G->senc.outBuf.size), (void *) SPHENC_FRAME_SIZE},

		/* Parameters for xdm 1.0 Video Encoder */
		{ "videnc1", "codec", DVEVM_ST_STR, G->venc1.venc1Name, DEFAULT_VIDENC1_NAME },
		{ "videnc1", "encodingPreset", DVEVM_ST_INT, &(G->venc1.venc1Params.encodingPreset), (void *) XDM_DEFAULT },
		{ "videnc1", "rateControlPreset", DVEVM_ST_INT, &(G->venc1.venc1Params.rateControlPreset), (void *) IVIDEO_LOW_DELAY },
		{ "videnc1", "maxHeight", DVEVM_ST_INT, &(G->venc1.venc1Params.maxHeight), (void *) VIDENC1_MAX_HT },
		{ "videnc1", "maxWidth", DVEVM_ST_INT, &(G->venc1.venc1Params.maxWidth), (void *) VIDENC1_MAX_WD },
		{ "videnc1", "maxFrameRate", DVEVM_ST_INT, &(G->venc1.venc1Params.maxFrameRate), (void *) VIDENC1_MAX_FR },
		{ "videnc1", "maxBitRate", DVEVM_ST_INT, &(G->venc1.venc1Params.maxBitRate), (void *) VIDENC1_MAX_BR },
		{ "videnc1", "dataEndianness", DVEVM_ST_INT, &(G->venc1.venc1Params.dataEndianness), (void *) XDM_BYTE },
		{ "videnc1", "maxInterFrameInterval", DVEVM_ST_INT, &(G->venc1.venc1Params.maxInterFrameInterval), (void *) XDM_DEFAULT },
		{ "videnc1", "inputChromaFormat", DVEVM_ST_INT, &(G->venc1.venc1Params.inputChromaFormat), (void *) XDM_YUV_420SP },
		{ "videnc1", "inputContentType", DVEVM_ST_INT, &(G->venc1.venc1Params.inputContentType), (void *) XDM_DEFAULT },
		{ "videnc1", "reconChromaFormat", DVEVM_ST_INT, &(G->venc1.venc1Params.reconChromaFormat), (void *) XDM_YUV_420SP },
		{ "videnc1", "topFieldFirstFlag", DVEVM_ST_INT, &(G->venc1.venc1InArgs.topFieldFirstFlag), (void *) 0 },
		{ "videnc1", "inputHeight", DVEVM_ST_INT, &(G->venc1.venc1DynParams.inputHeight), (void *) VIDENC1_MAX_HT },
		{ "videnc1", "inputWidth", DVEVM_ST_INT, &(G->venc1.venc1DynParams.inputWidth), (void *) VIDENC1_MAX_WD },
		{ "videnc1", "refFrameRate", DVEVM_ST_INT, &(G->venc1.venc1DynParams.refFrameRate), (void *) VIDENC1_MAX_FR },
		{ "videnc1", "targetFrameRate", DVEVM_ST_INT, &(G->venc1.venc1DynParams.targetFrameRate), (void *) VIDENC1_MAX_FR },
		{ "videnc1", "targetBitRate", DVEVM_ST_INT, &(G->venc1.venc1DynParams.targetBitRate), (void *) VIDENC1_MAX_BR },
		{ "videnc1", "intraFrameInterval", DVEVM_ST_INT, &(G->venc1.venc1DynParams.intraFrameInterval), (void *) VIDENC1_INTRA_FI },
		{ "videnc1", "generateHeader", DVEVM_ST_INT, &(G->venc1.venc1DynParams.generateHeader), (void *) XDM_ENCODE_AU },
		{ "videnc1", "captureWidth", DVEVM_ST_INT, &(G->venc1.venc1DynParams.captureWidth), (void *) 0 },
		{ "videnc1", "forceFrame", DVEVM_ST_INT, &(G->venc1.venc1DynParams.forceFrame), (void *) 0 },
		{ "videnc1", "interFrameInterval", DVEVM_ST_INT, &(G->venc1.venc1DynParams.interFrameInterval), (void *) 0 },
		{ "videnc1", "mbDataFlag", DVEVM_ST_INT, &(G->venc1.venc1DynParams.mbDataFlag), (void *) 0 },
		{ "videnc1", "numFrames", DVEVM_ST_INT, &(G->venc1.numFrames), (void *) DEF_CAP_FRAMES },

		/* Parameters for xdm 1.0 Image Encoder */
		{ "imgenc1", "codec", DVEVM_ST_STR, G->ienc1.ienc1Name, DEFAULT_IMGENC1_NAME },
		{ "imgenc1", "maxHeight", DVEVM_ST_INT, &(G->ienc1.ienc1Params.maxHeight), (void *) IMGENC1_MAX_HT },
		{ "imgenc1", "maxWidth", DVEVM_ST_INT, &(G->ienc1.ienc1Params.maxWidth), (void *) IMGENC1_MAX_WD },
		{ "imgenc1", "maxScans", DVEVM_ST_INT, &(G->ienc1.ienc1Params.maxScans), (void *) IMGENC1_MAX_SCANS },
		{ "imgenc1", "dataEndianness", DVEVM_ST_INT, &(G->ienc1.ienc1Params.dataEndianness), (void *) XDM_BYTE },
		{ "imgenc1", "forceChromaFormat", DVEVM_ST_INT, &(G->ienc1.ienc1Params.forceChromaFormat), (void *) XDM_YUV_422P },
		{ "imgenc1", "numAU", DVEVM_ST_INT, &(G->ienc1.ienc1DynParams.numAU), (void *) XDM_DEFAULT },
		{ "imgenc1", "inputChromaFormat", DVEVM_ST_INT, &(G->ienc1.ienc1DynParams.inputChromaFormat), (void *) XDM_YUV_422ILE },
		{ "imgenc1", "inputHeight", DVEVM_ST_INT, &(G->ienc1.ienc1DynParams.inputHeight), (void *) IMGENC1_MAX_HT },
		{ "imgenc1", "inputWidth", DVEVM_ST_INT, &(G->ienc1.ienc1DynParams.inputWidth), (void *) IMGENC1_MAX_WD },
		{ "imgenc1", "captureWidth", DVEVM_ST_INT, &(G->ienc1.ienc1DynParams.captureWidth), (void *) IMGENC1_MAX_WD },
		{ "imgenc1", "generateHeader", DVEVM_ST_INT, &(G->ienc1.ienc1DynParams.generateHeader), (void *) XDM_ENCODE_AU },
		{ "imgenc1", "qValue", DVEVM_ST_INT, &(G->ienc1.ienc1DynParams.qValue), (void *) 73 },

		/* Parameters for xdm 1.0 Image Decoder */
		{ "imgdec1", "codec", DVEVM_ST_STR, G->idec1.idec1Name, DEFAULT_IMGDEC1_NAME },
		{ "imgdec1", "maxHeight", DVEVM_ST_INT, &(G->idec1.idec1Params.maxHeight), (void *) IMGDEC1_MAX_HT },
		{ "imgdec1", "maxWidth", DVEVM_ST_INT, &(G->idec1.idec1Params.maxWidth), (void *) IMGDEC1_MAX_WD },
		{ "imgdec1", "maxScans", DVEVM_ST_INT, &(G->idec1.idec1Params.maxScans), (void *) IMGDEC1_MAX_SCANS },
		{ "imgdec1", "dataEndianness", DVEVM_ST_INT, &(G->idec1.idec1Params.dataEndianness), (void *) XDM_BYTE },
		{ "imgdec1", "forceChromaFormat", DVEVM_ST_INT, &(G->idec1.idec1Params.forceChromaFormat), (void *) XDM_YUV_422ILE },
		{ "imgdec1", "numAU", DVEVM_ST_INT, &(G->idec1.idec1DynParams.numAU), (void *) XDM_DEFAULT },
		{ "imgdec1", "decodeHeader", DVEVM_ST_INT, &(G->idec1.idec1DynParams.decodeHeader), (void *) XDM_DECODE_AU },
		{ "imgdec1", "displayWidth", DVEVM_ST_INT, &(G->idec1.idec1DynParams.displayWidth), (void *) XDM_DEFAULT },

		/* Parameters for AAC HE Encoder XDM 1.0 Base Params*/
		{ "audenc1", "codec", DVEVM_ST_STR, G->aenc1.audenc1Name, "aaclcenc1" },
		{ "audenc1", "seconds", DVEVM_ST_INT, &(G->aenc1.seconds), (void *) DEFAULT_AUDENC1_TIME },
		{ "audenc1", "sampleRate", DVEVM_ST_INT, &(G->aenc1.audenc1Params.sampleRate), (void *) 44100 },
		{ "audenc1", "bitRate", DVEVM_ST_INT, &(G->aenc1.audenc1Params.bitRate), (void *) 64000 },
		{ "audenc1", "channelMode", DVEVM_ST_INT, &(G->aenc1.audenc1Params.channelMode), (void *) IAUDIO_2_0 },
		{ "audenc1", "dataEndianness", DVEVM_ST_INT, &(G->aenc1.audenc1Params.dataEndianness), (void *) (XDAS_Int32)(XDM_LE_16) },
		{ "audenc1", "encMode", DVEVM_ST_INT, &(G->aenc1.audenc1Params.encMode), (void *) IAUDIO_CBR },
		{ "audenc1", "inputFormat", DVEVM_ST_INT, &(G->aenc1.audenc1Params.inputFormat), (void *) IAUDIO_INTERLEAVED },
		{ "audenc1", "inputBitsPerSample", DVEVM_ST_INT, &(G->aenc1.audenc1Params.inputBitsPerSample), (void *) 16 },
		{ "audenc1", "maxBitRate", DVEVM_ST_INT, &(G->aenc1.audenc1Params.maxBitRate), (void *) 144000 },
		{ "audenc1", "dualMonoMode", DVEVM_ST_INT, &(G->aenc1.audenc1Params.dualMonoMode), (void *) IAUDIO_DUALMONO_LR },
		{ "audenc1", "crcFlag", DVEVM_ST_INT, &(G->aenc1.audenc1Params.crcFlag), (void *) XDAS_FALSE },
		{ "audenc1", "ancFlag", DVEVM_ST_INT, &(G->aenc1.audenc1Params.ancFlag), (void *) XDAS_FALSE },
		{ "audenc1", "lfeFlag", DVEVM_ST_INT, &(G->aenc1.audenc1Params.lfeFlag), (void *) XDAS_FALSE },
		{ "audenc1", "dynamicparams.sampleRate", DVEVM_ST_INT, &(G->aenc1.audenc1DynParams.sampleRate), (void *) 44100 },
		{ "audenc1", "dynamicparams.bitRate", DVEVM_ST_INT, &(G->aenc1.audenc1DynParams.bitRate), (void *) 64000 },
		{ "audenc1", "dynamicparams.channelMode", DVEVM_ST_INT, &(G->aenc1.audenc1DynParams.channelMode), (void *) 1 },
		{ "audenc1", "dynamicparams.lfeFlag", DVEVM_ST_INT, &(G->aenc1.audenc1DynParams.lfeFlag), (void *) XDAS_FALSE },
		{ "audenc1", "dynamicparams.dualMonoMode", DVEVM_ST_INT, &(G->aenc1.audenc1DynParams.dualMonoMode), (void *) 0 },
		{ "audenc1", "dynamicparams.inputBitsPerSample", DVEVM_ST_INT, &(G->aenc1.audenc1DynParams.inputBitsPerSample), (void *) 16 },
		{ "audenc1", "InSamplesPerChannel", DVEVM_ST_INT, &(G->aenc1.InSamplesPerChannel), (void *) 1024 },

		/* Parameters for Audio Decoder 1.0 */
		{ "auddec1", "codec", DVEVM_ST_STR, G->adec1.adecName, "aacdec1" },
		{ "auddec1", "outputPCMWidth", DVEVM_ST_INT, &(G->adec1.adecParams.outputPCMWidth), (void *) AUDDEC1_PCM_WIDTH },
		{ "auddec1", "pcmFormat", DVEVM_ST_INT, &(G->adec1.adecParams.pcmFormat), (void *) IAUDIO_INTERLEAVED },
		{ "auddec1", "dataEndianness", DVEVM_ST_INT, &(G->adec1.adecParams.dataEndianness), (void *) XDM_LE_16 },
		{ "auddec1", "desiredChannelMode", DVEVM_ST_INT, &(G->adec1.desiredChannelMode), (void *) IAUDIO_2_0 },
		{ "auddec1", "lfeFlag", DVEVM_ST_INT, &(G->adec1.lfeFlag), (void *) 0 },
		{ "auddec1", "downSampleSbrFlag", DVEVM_ST_INT, &(G->adec1.adecDynParams.downSampleSbrFlag), (void *) 0 },
		{ "auddec1", "inbufsize", DVEVM_ST_INT, &(G->adec1.inBuf.bufSizes[0]), (void *) 10000 },
		{ "auddec1", "outbufsize", DVEVM_ST_INT, &(G->adec1.outBuf.bufSizes[0]), (void *) 16384 },

		/* Parameters for xdm 1.0 JPEG Encoder */
		{ "jpegenc1", "codec", DVEVM_ST_STR, G->jpegenc1.ienc1Name, "jpegenc1" },
		{ "jpegenc1", "maxHeight", DVEVM_ST_INT, &(G->jpegenc1.ienc1Params.imgencParams.maxHeight), (void *) IMGENC1_MAX_HT },
		{ "jpegenc1", "maxWidth", DVEVM_ST_INT, &(G->jpegenc1.ienc1Params.imgencParams.maxWidth), (void *) IMGENC1_MAX_WD },
		{ "jpegenc1", "maxScans", DVEVM_ST_INT, &(G->jpegenc1.ienc1Params.imgencParams.maxScans), (void *) IMGENC1_MAX_SCANS },
		{ "jpegenc1", "dataEndianness", DVEVM_ST_INT, &(G->jpegenc1.ienc1Params.imgencParams.dataEndianness), (void *) XDM_BYTE },
		{ "jpegenc1", "forceChromaFormat", DVEVM_ST_INT, &(G->jpegenc1.ienc1Params.imgencParams.forceChromaFormat), (void *) XDM_YUV_420SP },
		{ "jpegenc1", "numAU", DVEVM_ST_INT, &(G->jpegenc1.ienc1DynParams.imgencDynamicParams.numAU), (void *) XDM_DEFAULT },
		{ "jpegenc1", "inputChromaFormat", DVEVM_ST_INT, &(G->jpegenc1.ienc1DynParams.imgencDynamicParams.inputChromaFormat), (void *) XDM_YUV_422ILE },
		{ "jpegenc1", "inputHeight", DVEVM_ST_INT, &(G->jpegenc1.ienc1DynParams.imgencDynamicParams.inputHeight), (void *) IMGENC1_MAX_HT },
		{ "jpegenc1", "inputWidth", DVEVM_ST_INT, &(G->jpegenc1.ienc1DynParams.imgencDynamicParams.inputWidth), (void *) IMGENC1_MAX_WD },
		{ "jpegenc1", "captureWidth", DVEVM_ST_INT, &(G->jpegenc1.ienc1DynParams.imgencDynamicParams.captureWidth), (void *) IMGENC1_MAX_WD },
		{ "jpegenc1", "generateHeader", DVEVM_ST_INT, &(G->jpegenc1.ienc1DynParams.imgencDynamicParams.generateHeader), (void *) XDM_ENCODE_AU },
		{ "jpegenc1", "qValue", DVEVM_ST_INT, &(G->jpegenc1.ienc1DynParams.imgencDynamicParams.qValue), (void *) 73 },
		{ "jpegenc1", "halfBufCB", DVEVM_ST_INT, &(G->jpegenc1.ienc1Params.halfBufCB), (void *) NULL },
		{ "jpegenc1", "halfBufCBarg", DVEVM_ST_INT, &(G->jpegenc1.ienc1Params.halfBufCBarg), (void *) NULL },
		{ "jpegenc1", "extDynParamsRstInterval", DVEVM_ST_SHORT, &(G->jpegenc1.ienc1DynParams.rstInterval), (void *) 4 },
		{ "jpegenc1", "extDynParamsDisableEOI", DVEVM_ST_SHORT, &(G->jpegenc1.ienc1DynParams.disableEOI), (void *) XDM_DEFAULT },
		{ "jpegenc1", "extDynParamsRotation", DVEVM_ST_SHORT, &(G->jpegenc1.ienc1DynParams.rotation), (void *) XDM_DEFAULT },
		{ "jpegenc1", "customQ", DVEVM_ST_INT, &(G->jpegenc1.ienc1DynParams.customQ), (void *) NULL },

		/* Parameters for xdm 1.0 JPEG Decoder */
		{ "jpegdec1", "codec", DVEVM_ST_STR, G->jpegdec1.idec1Name, "jpegdec1" },
		{ "jpegdec1", "maxHeight", DVEVM_ST_INT, &(G->jpegdec1.idec1Params.imgdecParams.maxHeight), (void *) JPEGDEC1_MAX_HT },
		{ "jpegdec1", "maxWidth", DVEVM_ST_INT, &(G->jpegdec1.idec1Params.imgdecParams.maxWidth), (void *) JPEGDEC1_MAX_WD },
		{ "jpegdec1", "maxScans", DVEVM_ST_INT, &(G->jpegdec1.idec1Params.imgdecParams.maxScans), (void *) JPEGDEC1_MAX_SCANS },
		{ "jpegdec1", "dataEndianness", DVEVM_ST_INT, &(G->jpegdec1.idec1Params.imgdecParams.dataEndianness), (void *) XDM_BYTE },
		{ "jpegdec1", "forceChromaFormat", DVEVM_ST_INT, &(G->jpegdec1.idec1Params.imgdecParams.forceChromaFormat), (void *) XDM_YUV_422ILE },
		{ "jpegdec1", "numAU", DVEVM_ST_INT, &(G->jpegdec1.idec1DynParams.imgdecDynamicParams.numAU), (void *) XDM_DEFAULT },
		{ "jpegdec1", "decodeHeader", DVEVM_ST_INT, &(G->jpegdec1.idec1DynParams.imgdecDynamicParams.decodeHeader), (void *) XDM_DECODE_AU },
		{ "jpegdec1", "displayWidth", DVEVM_ST_INT, &(G->jpegdec1.idec1DynParams.imgdecDynamicParams.displayWidth), (void *) XDM_DEFAULT },

		{ "jpegdec1", "halfBufCB", DVEVM_ST_INT, &(G->jpegdec1.idec1Params.halfBufCB), (void *) 0 },
		{ "jpegdec1", "halfBufCBarg", DVEVM_ST_INT, &(G->jpegdec1.idec1Params.halfBufCBarg), (void *) 0 },
		{ "jpegdec1", "disableEOI", DVEVM_ST_SHORT, &(G->jpegdec1.idec1DynParams.disableEOI), (void *) 0 },
		{ "jpegdec1", "resizeOption", DVEVM_ST_INT, &(G->jpegdec1.idec1DynParams.resizeOption), (void *) 0 },
		{ "jpegdec1", "subRegionUpLeftX", DVEVM_ST_SHORT, &(G->jpegdec1.idec1DynParams.subRegionUpLeftX), (void *) XDM_DEFAULT },
		{ "jpegdec1", "subRegionUpLeftY", DVEVM_ST_SHORT, &(G->jpegdec1.idec1DynParams.subRegionUpLeftY), (void *) XDM_DEFAULT },
		{ "jpegdec1", "subRegionDownRightX", DVEVM_ST_SHORT, &(G->jpegdec1.idec1DynParams.subRegionDownRightX), (void *) XDM_DEFAULT },
		{ "jpegdec1", "subRegionDownRightY", DVEVM_ST_SHORT, &(G->jpegdec1.idec1DynParams.subRegionDownRightY), (void *) XDM_DEFAULT },
		{ "jpegdec1", "rotation", DVEVM_ST_SHORT, &(G->jpegdec1.idec1DynParams.rotation), (void *) 0 },
//		{ "jpegdec1", "decodingPreset", DVEVM_ST_SHORT, &(G->jpegdec1.idec1DynParams.decodingPreset), (void *) 0 },

		/* Parameters for Speech Encoder XDM 1.0 */
		{ "sphenc1", "codec", DVEVM_ST_STR, G->senc1.sencName, DEFAULT_SPHENC1_NAME },
		{ "sphenc1", "seconds", DVEVM_ST_INT, &(G->senc1.seconds), (void *) DEFAULT_SPHENC1_TIME },
		{ "sphenc1", "frameSize", DVEVM_ST_SHORT, &(G->senc1.sencParams.frameSize), (void *) SPHENC1_FRAME_SIZE },
		{ "sphenc1", "compandingLaw", DVEVM_ST_SHORT, &(G->senc1.sencParams.compandingLaw), (void *) SPHENC1_CL },
		{ "sphenc1", "packingType", DVEVM_ST_SHORT, &(G->senc1.sencParams.packingType), (void *) SPHENC1_PT },
		{ "sphenc1", "vadSelection", DVEVM_ST_SHORT, &(G->senc1.sencParams.vadSelection), (void *) SPHENC1_VS },
		{ "sphenc1", "codecSelection", DVEVM_ST_SHORT, &(G->senc1.sencParams.codecSelection), (void *) 0 },
		{ "sphenc1", "bitRate", DVEVM_ST_SHORT, &(G->senc1.sencParams.bitRate), (void *) 12000 },
		{ "sphenc1", "inbufsize", DVEVM_ST_INT, &(G->senc1.inBuf.size), (void *) (SPHENC1_FRAME_SIZE * 2) },
		{ "sphenc1", "outbufsize", DVEVM_ST_INT, &(G->senc1.outBuf.size), (void *) SPHENC1_FRAME_SIZE },

		/* Parameters for Speech Decoder XDM 1.0*/
		{ "sphdec1", "codec", DVEVM_ST_STR, G->sdec1.sdecName, DEFAULT_SPHDEC1_NAME },
		{ "sphdec1", "compandingLaw", DVEVM_ST_SHORT, &(G->sdec1.sdecParams.compandingLaw), (void *) SPHDEC1_CL },
		{ "sphdec1", "packingType", DVEVM_ST_SHORT, &(G->sdec1.sdecParams.packingType), (void *) SPHDEC1_PT },
		{ "sphdec1", "codecSelection", DVEVM_ST_SHORT, &(G->sdec1.sdecParams.codecSelection), (void *) 0 },
		{ "sphdec1", "bitRate", DVEVM_ST_SHORT, &(G->sdec1.sdecParams.bitRate), (void *) 12000 },
		{ "sphdec1", "inbufsize", DVEVM_ST_INT, &(G->sdec1.inBuf.size), (void *) SPHDEC1_INBUF_SIZE },
		{ "sphdec1", "outbufsize", DVEVM_ST_INT, &(G->sdec1.outBuf.size), (void *) SPHDEC1_OUTBUF_SIZE },

		/* Parameters for Video Decoder XDM 1.0*/

		{ "viddec2", "codec", DVEVM_ST_STR, G->vdec2.vdec2Name, DEFAULT_VIDDEC1_NAME },
		{ "viddec2", "maxHeight", DVEVM_ST_INT, &(G->vdec2.vdec2Params.maxHeight), (void *) VIDDEC2_MAX_HT },
		{ "viddec2", "maxWidth", DVEVM_ST_INT, &(G->vdec2.vdec2Params.maxWidth), (void *) VIDDEC2_MAX_WD },
		{ "viddec2", "maxFrameRate", DVEVM_ST_INT, &(G->vdec2.vdec2Params.maxFrameRate), (void *) VIDDEC2_MAX_FR },
		{ "viddec2", "maxBitRate", DVEVM_ST_INT, &(G->vdec2.vdec2Params.maxBitRate), (void *) VIDDEC2_MAX_BR },
		{ "viddec2", "dataEndianness", DVEVM_ST_INT, &(G->vdec2.vdec2Params.dataEndianness), (void *) XDM_BYTE },
		{ "viddec2", "forceChromaFormat", DVEVM_ST_INT, &(G->vdec2.vdec2Params.forceChromaFormat), (void *) XDM_YUV_420SP },
		{ "viddec2", "decodeHeader", DVEVM_ST_INT, &(G->vdec2.vdec2DynParams.decodeHeader), (void *) XDM_DECODE_AU },
		{ "viddec2", "displayWidth", DVEVM_ST_INT, &(G->vdec2.vdec2DynParams.displayWidth), (void *) XDM_DEFAULT },
		{ "viddec2", "frameSkipMode", DVEVM_ST_INT, &(G->vdec2.vdec2DynParams.frameSkipMode), (void *) IVIDEO_NO_SKIP },
		{ "viddec2", "frameOrder", DVEVM_ST_INT, &(G->vdec2.vdec2DynParams.frameOrder), (void *) IVIDDEC2_DISPLAY_ORDER },
		{ "viddec2", "newFrameFlag", DVEVM_ST_INT, &(G->vdec2.vdec2DynParams.newFrameFlag), (void *) 0 },
		{ "viddec2", "mbDataFlag", DVEVM_ST_INT, &(G->vdec2.vdec2DynParams.mbDataFlag), (void *) 0 },
		{ "viddec2", "numFrames", DVEVM_ST_INT, &(G->vdec2.numFrames), (void *) DEF_CAP_FRAMES },

		/* Parameters for H264 Decoder XDM 1.0*/
		{ "h264dec2", "codec", DVEVM_ST_STR, G->h264dec2.h264dec2Name, "h264dec2" },
		{ "h264dec2", "maxHeight", DVEVM_ST_INT, &(G->h264dec2.vdec2Params.viddecParams.maxHeight), (void *) VIDDEC2_MAX_HT },
		{ "h264dec2", "maxWidth", DVEVM_ST_INT, &(G->h264dec2.vdec2Params.viddecParams.maxWidth), (void *) VIDDEC2_MAX_WD },
		{ "h264dec2", "maxFrameRate", DVEVM_ST_INT, &(G->h264dec2.vdec2Params.viddecParams.maxFrameRate), (void *) VIDDEC2_MAX_FR },
		{ "h264dec2", "maxBitRate", DVEVM_ST_INT, &(G->h264dec2.vdec2Params.viddecParams.maxBitRate), (void *) VIDDEC2_MAX_BR },
		{ "h264dec2", "dataEndianness", DVEVM_ST_INT, &(G->h264dec2.vdec2Params.viddecParams.dataEndianness), (void *) XDM_BYTE },
		{ "h264dec2", "forceChromaFormat", DVEVM_ST_INT, &(G->h264dec2.vdec2Params.viddecParams.forceChromaFormat), (void *) XDM_YUV_420SP },
		{ "h264dec2", "decodeHeader", DVEVM_ST_INT, &(G->h264dec2.vdec2DynParams.viddecDynamicParams.decodeHeader), (void *) XDM_DECODE_AU },
		{ "h264dec2", "displayWidth", DVEVM_ST_INT, &(G->h264dec2.vdec2DynParams.viddecDynamicParams.displayWidth), (void *) XDM_DEFAULT },
		{ "h264dec2", "frameSkipMode", DVEVM_ST_INT, &(G->h264dec2.vdec2DynParams.viddecDynamicParams.frameSkipMode), (void *) IVIDEO_NO_SKIP },
		{ "h264dec2", "frameOrder", DVEVM_ST_INT, &(G->h264dec2.vdec2DynParams.viddecDynamicParams.frameOrder), (void *) IVIDDEC2_DISPLAY_ORDER },
		{ "h264dec2", "newFrameFlag", DVEVM_ST_INT, &(G->h264dec2.vdec2DynParams.viddecDynamicParams.newFrameFlag), (void *) 0 },
		{ "h264dec2", "mbDataFlag", DVEVM_ST_INT, &(G->h264dec2.vdec2DynParams.viddecDynamicParams.mbDataFlag), (void *) 0 },
		{ "h264dec2", "numFrames", DVEVM_ST_INT, &(G->h264dec2.numFrames), (void *) DEF_CAP_FRAMES },
		{ "h264dec2", "displayDelay", DVEVM_ST_INT, &(G->h264dec2.vdec2Params.displayDelay), (void *) 16 },
		{ "h264dec2", "hdvicpHandle", DVEVM_ST_INT, &(G->h264dec2.vdec2Params.hdvicpHandle), (void *) NULL },
		{ "h264dec2", "disableHDVICPeveryFrame", DVEVM_ST_CHAR, &(G->h264dec2.vdec2Params.disableHDVICPeveryFrame), (void *) 1 },
		{ "h264dec2", "inputDataMode", DVEVM_ST_INT, &(G->h264dec2.vdec2Params.inputDataMode), (void *) 1 },
		{ "h264dec2", "sliceFormat", DVEVM_ST_INT, &(G->h264dec2.vdec2Params.sliceFormat), (void *) 1 },
		{ "h264dec2", "resetHDVICPeveryFrame", DVEVM_ST_CHAR, &(G->h264dec2.vdec2DynParams.resetHDVICPeveryFrame), (void *) 1 },
		{ "h264dec2", "getDataFxn", DVEVM_ST_INT, &(G->h264dec2.vdec2DynParams.getDataFxn), (void *) NULL },
		{ "h264dec2", "dataSyncHandle", DVEVM_ST_INT, &(G->h264dec2.vdec2DynParams.dataSyncHandle), (void *) NULL },

		/* Parameters for MPEG2 Decoder XDM 1.2*/
		{ "mpeg2dec2", "codec", DVEVM_ST_STR, G->mpeg2dec2.mpeg2dec2Name, DEFAULT_MPEG2DEC2_NAME },
		{ "mpeg2dec2", "maxHeight", DVEVM_ST_INT, &(G->mpeg2dec2.vdec2Params.viddecParams.maxHeight), (void *) VIDDEC2_MAX_HT },
		{ "mpeg2dec2", "maxWidth", DVEVM_ST_INT, &(G->mpeg2dec2.vdec2Params.viddecParams.maxWidth), (void *) VIDDEC2_MAX_WD },
		{ "mpeg2dec2", "maxFrameRate", DVEVM_ST_INT, &(G->mpeg2dec2.vdec2Params.viddecParams.maxFrameRate), (void *) VIDDEC2_MAX_FR },
		{ "mpeg2dec2", "maxBitRate", DVEVM_ST_INT, &(G->mpeg2dec2.vdec2Params.viddecParams.maxBitRate), (void *) VIDDEC2_MAX_BR },
		{ "mpeg2dec2", "dataEndianness", DVEVM_ST_INT, &(G->mpeg2dec2.vdec2Params.viddecParams.dataEndianness), (void *) XDM_BYTE },
		{ "mpeg2dec2", "forceChromaFormat", DVEVM_ST_INT, &(G->mpeg2dec2.vdec2Params.viddecParams.forceChromaFormat), (void *) XDM_YUV_420SP },
		{ "mpeg2dec2", "display_delay", DVEVM_ST_INT, &(G->mpeg2dec2.vdec2Params.display_delay), (void *) 1 },
		{ "mpeg2dec2", "decodeHeader", DVEVM_ST_INT, &(G->mpeg2dec2.vdec2DynParams.viddecDynamicParams.decodeHeader), (void *) XDM_DECODE_AU },
		{ "mpeg2dec2", "displayWidth", DVEVM_ST_INT, &(G->mpeg2dec2.vdec2DynParams.viddecDynamicParams.displayWidth), (void *) XDM_DEFAULT },
		{ "mpeg2dec2", "frameSkipMode", DVEVM_ST_INT, &(G->mpeg2dec2.vdec2DynParams.viddecDynamicParams.frameSkipMode), (void *) IVIDEO_NO_SKIP },
		{ "mpeg2dec2", "frameOrder", DVEVM_ST_INT, &(G->mpeg2dec2.vdec2DynParams.viddecDynamicParams.frameOrder), (void *) 0 },
		{ "mpeg2dec2", "newFrameFlag", DVEVM_ST_INT, &(G->mpeg2dec2.vdec2DynParams.viddecDynamicParams.newFrameFlag), (void *) 0 },
		{ "mpeg2dec2", "mbDataFlag", DVEVM_ST_INT, &(G->mpeg2dec2.vdec2DynParams.viddecDynamicParams.mbDataFlag), (void *) 0 },
		{ "mpeg2dec2", "bottom_fld_DDR_Opt", DVEVM_ST_CHAR, &(G->mpeg2dec2.vdec2DynParams.bottom_fld_DDR_Opt), (void *) 0 },
		{ "mpeg2dec2", "mb_error_reporting", DVEVM_ST_CHAR, &(G->mpeg2dec2.vdec2DynParams.mb_error_reporting), (void *) 0 },
		{ "mpeg2dec2", "errorConceal", DVEVM_ST_INT, &(G->mpeg2dec2.vdec2DynParams.errorConceal), (void *) 1 },
		{ "mpeg2dec2", "reset_HDVICP_every_frame", DVEVM_ST_CHAR, &(G->mpeg2dec2.vdec2DynParams.reset_HDVICP_every_frame), (void *) 1 },
		{ "mpeg2dec2", "numFrames", DVEVM_ST_INT, &(G->mpeg2dec2.numFrames), (void *) 100 },

		/* Parameters for Mpeg4 Decoder XDM 1.0*/
		{ "mpeg4dec2", "codec", DVEVM_ST_STR, G->mpeg4dec2.mpeg4dec2Name, "mpeg4dec2" },
		{ "mpeg4dec2", "maxHeight", DVEVM_ST_INT, &(G->mpeg4dec2.vdec2Params.viddecParams.maxHeight), (void *) VIDDEC2_MAX_HT },
		{ "mpeg4dec2", "maxWidth", DVEVM_ST_INT, &(G->mpeg4dec2.vdec2Params.viddecParams.maxWidth), (void *) VIDDEC2_MAX_WD },
		{ "mpeg4dec2", "maxFrameRate", DVEVM_ST_INT, &(G->mpeg4dec2.vdec2Params.viddecParams.maxFrameRate), (void *) VIDDEC2_MAX_FR },
		{ "mpeg4dec2", "maxBitRate", DVEVM_ST_INT, &(G->mpeg4dec2.vdec2Params.viddecParams.maxBitRate), (void *) VIDDEC2_MAX_BR },
		{ "mpeg4dec2", "dataEndianness", DVEVM_ST_INT, &(G->mpeg4dec2.vdec2Params.viddecParams.dataEndianness), (void *) XDM_BYTE },
		{ "mpeg4dec2", "forceChromaFormat", DVEVM_ST_INT, &(G->mpeg4dec2.vdec2Params.viddecParams.forceChromaFormat), (void *) XDM_YUV_422ILE },
		{ "mpeg4dec2", "decodeHeader", DVEVM_ST_INT, &(G->mpeg4dec2.vdec2DynParams.viddecDynamicParams.decodeHeader), (void *) XDM_DECODE_AU },
		{ "mpeg4dec2", "displayWidth", DVEVM_ST_INT, &(G->mpeg4dec2.vdec2DynParams.viddecDynamicParams.displayWidth), (void *) XDM_DEFAULT },
		{ "mpeg4dec2", "frameSkipMode", DVEVM_ST_INT, &(G->mpeg4dec2.vdec2DynParams.viddecDynamicParams.frameSkipMode), (void *) IVIDEO_NO_SKIP },
		{ "mpeg4dec2", "frameOrder", DVEVM_ST_INT, &(G->mpeg4dec2.vdec2DynParams.viddecDynamicParams.frameOrder), (void *) 0 },
		{ "mpeg4dec2", "newFrameFlag", DVEVM_ST_INT, &(G->mpeg4dec2.vdec2DynParams.viddecDynamicParams.newFrameFlag), (void *) 0 },
		{ "mpeg4dec2", "mbDataFlag", DVEVM_ST_INT, &(G->mpeg4dec2.vdec2DynParams.viddecDynamicParams.mbDataFlag), (void *) 80 },
		{ "mpeg4dec2", "extmeRange", DVEVM_ST_INT, &(G->mpeg4dec2.vdec2Params.meRange), (void *) 31 },
		{ "mpeg4dec2", "extdisplayWidth", DVEVM_ST_INT, &(G->mpeg4dec2.vdec2Params.displayWidth), (void *) 0 },
		{ "mpeg4dec2", "extrotation", DVEVM_ST_INT, &(G->mpeg4dec2.vdec2Params.rotation), (void *) 0 },
		{ "mpeg4dec2", "extunrestrictedMV", DVEVM_ST_INT, &(G->mpeg4dec2.vdec2Params.unrestrictedMV), (void *) 1 },
		{ "mpeg4dec2", "numFrames", DVEVM_ST_INT, &(G->mpeg4dec2.numFrames), (void *) DEF_CAP_FRAMES },

		/* Parameters for Mpeg4 HDVICP Decoder XDM 1.0*/
		{ "mpeg4hdvicpdec2", "codec", DVEVM_ST_STR, G->mpeg4hdvicpdec2.mpeg4dec2Name, "mpeg4hdvicpdec2" },
		{ "mpeg4hdvicpdec2", "maxHeight", DVEVM_ST_INT, &(G->mpeg4hdvicpdec2.vdec2Params.viddecParams.maxHeight), (void *) VIDDEC2_MAX_HT },
		{ "mpeg4hdvicpdec2", "maxWidth", DVEVM_ST_INT, &(G->mpeg4hdvicpdec2.vdec2Params.viddecParams.maxWidth), (void *) VIDDEC2_MAX_WD },
		{ "mpeg4hdvicpdec2", "maxFrameRate", DVEVM_ST_INT, &(G->mpeg4hdvicpdec2.vdec2Params.viddecParams.maxFrameRate), (void *) VIDDEC2_MAX_FR },
		{ "mpeg4hdvicpdec2", "maxBitRate", DVEVM_ST_INT, &(G->mpeg4hdvicpdec2.vdec2Params.viddecParams.maxBitRate), (void *) VIDDEC2_MAX_BR },
		{ "mpeg4hdvicpdec2", "dataEndianness", DVEVM_ST_INT, &(G->mpeg4hdvicpdec2.vdec2Params.viddecParams.dataEndianness), (void *) XDM_BYTE },
		{ "mpeg4hdvicpdec2", "forceChromaFormat", DVEVM_ST_INT, &(G->mpeg4hdvicpdec2.vdec2Params.viddecParams.forceChromaFormat), (void *) XDM_YUV_422ILE },
		{ "mpeg4hdvicpdec2", "decodeHeader", DVEVM_ST_INT, &(G->mpeg4hdvicpdec2.vdec2DynParams.viddecDynamicParams.decodeHeader), (void *) XDM_DECODE_AU },
		{ "mpeg4hdvicpdec2", "displayWidth", DVEVM_ST_INT, &(G->mpeg4hdvicpdec2.vdec2DynParams.viddecDynamicParams.displayWidth), (void *) XDM_DEFAULT },
		{ "mpeg4hdvicpdec2", "frameSkipMode", DVEVM_ST_INT, &(G->mpeg4hdvicpdec2.vdec2DynParams.viddecDynamicParams.frameSkipMode), (void *) IVIDEO_NO_SKIP },
		{ "mpeg4hdvicpdec2", "frameOrder", DVEVM_ST_INT, &(G->mpeg4hdvicpdec2.vdec2DynParams.viddecDynamicParams.frameOrder), (void *) 0 },
		{ "mpeg4hdvicpdec2", "newFrameFlag", DVEVM_ST_INT, &(G->mpeg4hdvicpdec2.vdec2DynParams.viddecDynamicParams.newFrameFlag), (void *) 0 },
		{ "mpeg4hdvicpdec2", "mbDataFlag", DVEVM_ST_INT, &(G->mpeg4hdvicpdec2.vdec2DynParams.viddecDynamicParams.mbDataFlag), (void *) 80 },
		{ "mpeg4hdvicpdec2", "extdisplayDelay", DVEVM_ST_INT, &(G->mpeg4hdvicpdec2.vdec2Params.displayDelay), (void *) 1 },
		{ "mpeg4hdvicpdec2", "extdisableHDVICPeveryFrame", DVEVM_ST_CHAR, &(G->mpeg4hdvicpdec2.vdec2Params.disableHDVICPeveryFrame), (void *) 0 },
		{ "mpeg4hdvicpdec2", "extoutloopDeblocking", DVEVM_ST_INT, &(G->mpeg4hdvicpdec2.vdec2DynParams.outloopDeblocking), (void *) 0 },
		{ "mpeg4hdvicpdec2", "extoutloopDeRinging", DVEVM_ST_INT, &(G->mpeg4hdvicpdec2.vdec2DynParams.outloopDeRinging), (void *) 0 },
		{ "mpeg4hdvicpdec2", "extresetHDVICPeveryFrame", DVEVM_ST_CHAR, &(G->mpeg4hdvicpdec2.vdec2DynParams.resetHDVICPeveryFrame), (void *) 1 },
		{ "mpeg4hdvicpdec2", "numFrames", DVEVM_ST_INT, &(G->mpeg4hdvicpdec2.numFrames), (void *) DEF_CAP_FRAMES },

		/* Parameters for VC1 Decoder XDM 1.0*/
		{ "vc1dec2", "codec", DVEVM_ST_STR, G->vc1dec2.vc1dec2Name, "vc1dec2" },
		{ "vc1dec2", "maxHeight", DVEVM_ST_INT, &(G->vc1dec2.vdec2Params.viddecParams.maxHeight), (void *) VIDDEC2_MAX_HT },
		{ "vc1dec2", "maxWidth", DVEVM_ST_INT, &(G->vc1dec2.vdec2Params.viddecParams.maxWidth), (void *) VIDDEC2_MAX_WD },
		{ "vc1dec2", "maxFrameRate", DVEVM_ST_INT, &(G->vc1dec2.vdec2Params.viddecParams.maxFrameRate), (void *) VIDDEC2_MAX_FR },
		{ "vc1dec2", "maxBitRate", DVEVM_ST_INT, &(G->vc1dec2.vdec2Params.viddecParams.maxBitRate), (void *) VIDDEC2_MAX_BR },
		{ "vc1dec2", "dataEndianness", DVEVM_ST_INT, &(G->vc1dec2.vdec2Params.viddecParams.dataEndianness), (void *) XDM_BYTE },
		{ "vc1dec2", "forceChromaFormat", DVEVM_ST_INT, &(G->vc1dec2.vdec2Params.viddecParams.forceChromaFormat), (void *) XDM_YUV_422ILE },
		{ "vc1dec2", "decodeHeader", DVEVM_ST_INT, &(G->vc1dec2.vdec2DynParams.viddecDynamicParams.decodeHeader), (void *) XDM_DECODE_AU },
		{ "vc1dec2", "displayWidth", DVEVM_ST_INT, &(G->vc1dec2.vdec2DynParams.viddecDynamicParams.displayWidth), (void *) XDM_DEFAULT },
		{ "vc1dec2", "frameSkipMode", DVEVM_ST_INT, &(G->vc1dec2.vdec2DynParams.viddecDynamicParams.frameSkipMode), (void *) IVIDEO_NO_SKIP },
		{ "vc1dec2", "frameOrder", DVEVM_ST_INT, &(G->vc1dec2.vdec2DynParams.viddecDynamicParams.frameOrder), (void *) 0 },
		{ "vc1dec2", "newFrameFlag", DVEVM_ST_INT, &(G->vc1dec2.vdec2DynParams.viddecDynamicParams.newFrameFlag), (void *) 0 },
		{ "vc1dec2", "mbDataFlag", DVEVM_ST_INT, &(G->vc1dec2.vdec2DynParams.viddecDynamicParams.mbDataFlag), (void *) 0 },
		{ "vc1dec2", "display_delay", DVEVM_ST_INT, &(G->vc1dec2.vdec2Params.display_delay), (void *) 1 },
		{ "vc1dec2", "rcvParseInLib", DVEVM_ST_CHAR, &(G->vc1dec2.vdec2Params.rcvParseInLib), (void *) 1 },
		{ "vc1dec2", "streamType", DVEVM_ST_CHAR, &(G->vc1dec2.vdec2Params.streamType), (void *) 0 },
		{ "vc1dec2", "outloopDeblocking", DVEVM_ST_INT, &(G->vc1dec2.vdec2DynParams.outloopDeblocking), (void *) 0 },
		{ "vc1dec2", "reset_HDVICP_every_frame", DVEVM_ST_CHAR, &(G->vc1dec2.vdec2DynParams.reset_HDVICP_every_frame), (void *) 1 },
		{ "vc1dec2", "numFrames", DVEVM_ST_INT, &(G->vc1dec2.numFrames), (void *) DEF_CAP_FRAMES },

		/* Parameters for xdm 1.0 H264 Encoder */
		{ "h264enc1", "codec", DVEVM_ST_STR, G->h264enc1.h264enc1Name, "h264enc1" },
		{ "h264enc1", "encodingPreset", DVEVM_ST_INT, &(G->h264enc1.venc1Params.videncParams.encodingPreset), (void *) 3 },
		{ "h264enc1", "rateControlPreset", DVEVM_ST_INT, &(G->h264enc1.venc1Params.videncParams.rateControlPreset), (void *) 5 },
		{ "h264enc1", "maxHeight", DVEVM_ST_INT, &(G->h264enc1.venc1Params.videncParams.maxHeight), (void *) H264ENC1_MAX_HT },
		{ "h264enc1", "maxWidth", DVEVM_ST_INT, &(G->h264enc1.venc1Params.videncParams.maxWidth), (void *) H264ENC1_MAX_WD },
		{ "h264enc1", "maxFrameRate", DVEVM_ST_INT, &(G->h264enc1.venc1Params.videncParams.maxFrameRate), (void *) H264ENC1_MAX_FR },
		{ "h264enc1", "maxBitRate", DVEVM_ST_INT, &(G->h264enc1.venc1Params.videncParams.maxBitRate), (void *) H264ENC1_MAX_BR },
		{ "h264enc1", "dataEndianness", DVEVM_ST_INT, &(G->h264enc1.venc1Params.videncParams.dataEndianness), (void *) XDM_BYTE },
		{ "h264enc1", "maxInterFrameInterval", DVEVM_ST_INT, &(G->h264enc1.venc1Params.videncParams.maxInterFrameInterval), (void *) XDM_DEFAULT },
		{ "h264enc1", "inputChromaFormat", DVEVM_ST_INT, &(G->h264enc1.venc1Params.videncParams.inputChromaFormat), (void *) XDM_YUV_420SP },
		{ "h264enc1", "inputContentType", DVEVM_ST_INT, &(G->h264enc1.venc1Params.videncParams.inputContentType), (void *) XDM_DEFAULT },
		{ "h264enc1", "reconChromaFormat", DVEVM_ST_INT, &(G->h264enc1.venc1Params.videncParams.reconChromaFormat), (void *) XDM_YUV_420SP },
		{ "h264enc1", "topFieldFirstFlag", DVEVM_ST_INT, &(G->h264enc1.venc1InArgs.videncInArgs.topFieldFirstFlag), (void *) 0 },
		{ "h264enc1", "inputHeight", DVEVM_ST_INT, &(G->h264enc1.venc1DynParams.videncDynamicParams.inputHeight), (void *) H264ENC1_MAX_HT },
		{ "h264enc1", "inputWidth", DVEVM_ST_INT, &(G->h264enc1.venc1DynParams.videncDynamicParams.inputWidth), (void *) H264ENC1_MAX_WD },
		{ "h264enc1", "refFrameRate", DVEVM_ST_INT, &(G->h264enc1.venc1DynParams.videncDynamicParams.refFrameRate), (void *) H264ENC1_MAX_FR },
		{ "h264enc1", "targetFrameRate", DVEVM_ST_INT, &(G->h264enc1.venc1DynParams.videncDynamicParams.targetFrameRate), (void *) H264ENC1_MAX_FR },
		{ "h264enc1", "targetBitRate", DVEVM_ST_INT, &(G->h264enc1.venc1DynParams.videncDynamicParams.targetBitRate), (void *) H264ENC1_MAX_BR },
		{ "h264enc1", "intraFrameInterval", DVEVM_ST_INT, &(G->h264enc1.venc1DynParams.videncDynamicParams.intraFrameInterval), (void *) 30 },
		{ "h264enc1", "generateHeader", DVEVM_ST_INT, &(G->h264enc1.venc1DynParams.videncDynamicParams.generateHeader), (void *) XDM_ENCODE_AU },
		{ "h264enc1", "captureWidth", DVEVM_ST_INT, &(G->h264enc1.venc1DynParams.videncDynamicParams.captureWidth), (void *) 0 },
		{ "h264enc1", "forceFrame", DVEVM_ST_INT, &(G->h264enc1.venc1DynParams.videncDynamicParams.forceFrame), (void *) 0 },
		{ "h264enc1", "interFrameInterval", DVEVM_ST_INT, &(G->h264enc1.venc1DynParams.videncDynamicParams.interFrameInterval), (void *) 0 },
		{ "h264enc1", "mbDataFlag", DVEVM_ST_INT, &(G->h264enc1.venc1DynParams.videncDynamicParams.mbDataFlag), (void *) 0 },
		{ "h264enc1", "numFrames", DVEVM_ST_INT, &(G->h264enc1.numFrames), (void *) DEF_CAP_FRAMES },

		{ "h264enc1", "profileIdc", DVEVM_ST_INT, &(G->h264enc1.venc1Params.profileIdc), (void *) 100 },
		{ "h264enc1", "levelIdc", DVEVM_ST_INT, &(G->h264enc1.venc1Params.levelIdc), (void *) IH264VENC_LEVEL_40 },
		{ "h264enc1", "meAlgo", DVEVM_ST_INT, &(G->h264enc1.venc1Params.meAlgo), (void *) 0 },
		{ "h264enc1", "enableVUIparams", DVEVM_ST_INT, &(G->h264enc1.venc1Params.enableVUIparams), (void *) 0 },
		{ "h264enc1", "EntropyMode", DVEVM_ST_INT, &(G->h264enc1.venc1Params.entropyMode), (void *) 1 },
		{ "h264enc1", "Transform8x8FlagIntraFrame", DVEVM_ST_INT, &(G->h264enc1.venc1Params.transform8x8FlagIntraFrame), (void *) 1 },
		{ "h264enc1", "Transform8x8FlagInterFrame", DVEVM_ST_INT, &(G->h264enc1.venc1Params.transform8x8FlagInterFrame), (void *) 0 },
		{ "h264enc1", "EnableLongTermFrame", DVEVM_ST_INT, &(G->h264enc1.venc1Params.EnableLongTermFrame), (void *) 0 },
		{ "h264enc1", "ConstraintSetFlag", DVEVM_ST_INT, &(G->h264enc1.venc1Params.ConstraintSetFlag), (void *) 0 },
		{ "h264enc1", "Log2MaxFrameNumMinus4", DVEVM_ST_INT, &(G->h264enc1.venc1Params.Log2MaxFrameNumMinus4), (void *) 0 },
		{ "h264enc1", "svcSyntaxEnable", DVEVM_ST_INT, &(G->h264enc1.venc1Params.svcSyntaxEnable), (void *) 0 },
		{ "h264enc1", "numTemporalLayers", DVEVM_ST_INT, &(G->h264enc1.venc1Params.numTemporalLayers), (void *) 0 },
		{ "h264enc1", "SeqScalingFlag", DVEVM_ST_INT, &(G->h264enc1.venc1Params.seqScalingFlag), (void *) 1 },
		{ "h264enc1", "EncQuality", DVEVM_ST_INT, &(G->h264enc1.venc1Params.encQuality), (void *) 0 },
		{ "h264enc1", "enableARM926Tcm", DVEVM_ST_INT, &(G->h264enc1.venc1Params.enableARM926Tcm), (void *) 0 },
		{ "h264enc1", "enableDDRbuff", DVEVM_ST_INT, &(G->h264enc1.venc1Params.enableDDRbuff), (void *) 0 },
		{ "h264enc1", "sliceMode", DVEVM_ST_INT, &(G->h264enc1.venc1Params.sliceMode), (void *) 0 },
		{ "h264enc1", "outputDataMode", DVEVM_ST_INT, &(G->h264enc1.venc1Params.outputDataMode), (void *) IH264VENC_TI_ENTIREFRAME },
		{ "h264enc1", "sliceFormat", DVEVM_ST_INT, &(G->h264enc1.venc1Params.sliceFormat), (void *) 1 },

		{ "h264enc1", "sliceSize", DVEVM_ST_INT, &(G->h264enc1.venc1DynParams.sliceSize), (void *) 0 },
		{ "h264enc1", "airRate", DVEVM_ST_INT, &(G->h264enc1.venc1DynParams.airRate), (void *) 0 },
		{ "h264enc1", "initQ", DVEVM_ST_INT, &(G->h264enc1.venc1DynParams.initQ), (void *) 28 },
		{ "h264enc1", "intraFrameQP", DVEVM_ST_INT, &(G->h264enc1.venc1DynParams.intraFrameQP), (void *) 28 },
		{ "h264enc1", "interPFrameQP", DVEVM_ST_INT, &(G->h264enc1.venc1DynParams.interPFrameQP), (void *) 28 },
		{ "h264enc1", "rcQMax", DVEVM_ST_INT, &(G->h264enc1.venc1DynParams.rcQMax), (void *) 45 },
		{ "h264enc1", "rcQMin", DVEVM_ST_INT, &(G->h264enc1.venc1DynParams.rcQMin), (void *) 0 },
		{ "h264enc1", "rcQMaxI", DVEVM_ST_INT, &(G->h264enc1.venc1DynParams.rcQMaxI), (void *) 42 },
		{ "h264enc1", "rcQMinI", DVEVM_ST_INT, &(G->h264enc1.venc1DynParams.rcQMinI), (void *) 0 },
		{ "h264enc1", "rcAlgo", DVEVM_ST_INT, &(G->h264enc1.venc1DynParams.rcAlgo), (void *) 1 },
		{ "h264enc1", "maxDelay", DVEVM_ST_INT, &(G->h264enc1.venc1DynParams.maxDelay), (void *) 2000 },		
		{ "h264enc1", "lfDisableIdc", DVEVM_ST_INT, &(G->h264enc1.venc1DynParams.lfDisableIdc), (void *) 0 },		
		{ "h264enc1", "aspectRatioX", DVEVM_ST_INT, &(G->h264enc1.venc1DynParams.aspectRatioX), (void *) 1 },
		{ "h264enc1", "aspectRatioY", DVEVM_ST_INT, &(G->h264enc1.venc1DynParams.aspectRatioY), (void *) 1 },
		{ "h264enc1", "enableBufSEI", DVEVM_ST_INT, &(G->h264enc1.venc1DynParams.enableBufSEI), (void *) 0 },
		{ "h264enc1", "enablePicTimSEI", DVEVM_ST_INT, &(G->h264enc1.venc1DynParams.enablePicTimSEI), (void *) 0 },
		{ "h264enc1", "perceptualRC", DVEVM_ST_INT, &(G->h264enc1.venc1DynParams.perceptualRC), (void *) 1 },
		{ "h264enc1", "idrFrameInterval", DVEVM_ST_INT, &(G->h264enc1.venc1DynParams.idrFrameInterval), (void *) 0 },
		{ "h264enc1", "mvSADoutFlag", DVEVM_ST_INT, &(G->h264enc1.venc1DynParams.mvSADoutFlag), (void *) 0 },
		{ "h264enc1", "resetHDVICPeveryFrame", DVEVM_ST_INT, &(G->h264enc1.venc1DynParams.resetHDVICPeveryFrame), (void *) 1 },
		{ "h264enc1", "enableROI", DVEVM_ST_INT, &(G->h264enc1.venc1DynParams.enableROI), (void *) 0 },
		{ "h264enc1", "metaDataGenerateConsume", DVEVM_ST_INT, &(G->h264enc1.venc1DynParams.metaDataGenerateConsume), (void *) 0 },
		{ "h264enc1", "maxBitrateCVBR", DVEVM_ST_INT, &(G->h264enc1.venc1DynParams.maxBitrateCVBR), (void *) H264ENC1_MAX_BR },
		{ "h264enc1", "maxHighCmpxIntCVBR", DVEVM_ST_INT, &(G->h264enc1.venc1DynParams.maxHighCmpxIntCVBR), (void *) 0 },
		{ "h264enc1", "CVBRsensitivity", DVEVM_ST_INT, &(G->h264enc1.venc1DynParams.CVBRsensitivity), (void *) 0 },
		{ "h264enc1", "LBRmaxpicsize", DVEVM_ST_INT, &(G->h264enc1.venc1DynParams.LBRmaxpicsize), (void *) 0 },
		{ "h264enc1", "LBRminpicsize", DVEVM_ST_INT, &(G->h264enc1.venc1DynParams.LBRminpicsize), (void *) 0 },
		{ "h264enc1", "LBRskipcontrol", DVEVM_ST_INT, &(G->h264enc1.venc1DynParams.LBRskipcontrol), (void *) 327684 },
		{ "h264enc1", "interlaceRefMode", DVEVM_ST_INT, &(G->h264enc1.venc1DynParams.interlaceRefMode), (void *) 0 },
		{ "h264enc1", "LongTermRefreshInterval", DVEVM_ST_INT, &(G->h264enc1.venc1DynParams.LongTermRefreshInterval), (void *) 0 },
		{ "h264enc1", "UseLongTermFrame", DVEVM_ST_INT, &(G->h264enc1.venc1DynParams.UseLongTermFrame), (void *) 0 },
		{ "h264enc1", "SetLongTermFrame", DVEVM_ST_INT, &(G->h264enc1.venc1DynParams.SetLongTermFrame), (void *) 0 },
		{ "h264enc1", "enableGDR", DVEVM_ST_INT, &(G->h264enc1.venc1DynParams.enableGDR), (void *) 0 },
		{ "h264enc1", "GDRduration", DVEVM_ST_INT, &(G->h264enc1.venc1DynParams.GDRduration), (void *) 5 },
		{ "h264enc1", "GDRinterval", DVEVM_ST_INT, &(G->h264enc1.venc1DynParams.GDRinterval), (void *) 30 },
		{ "h264enc1", "numOfROI", DVEVM_ST_INT, &(G->h264enc1.venc1InArgs.roiParameters.numOfROI), (void *) 0 },
		{ "h264enc1", "listROI[0].topLeft.x", DVEVM_ST_INT, &(G->h264enc1.venc1InArgs.roiParameters.listROI[0].topLeft.x), (void *) 0 },
		{ "h264enc1", "listROI[0].topLeft.y", DVEVM_ST_INT, &(G->h264enc1.venc1InArgs.roiParameters.listROI[0].topLeft.y), (void *) 0 },
		{ "h264enc1", "listROI[0].bottomRight.x", DVEVM_ST_INT, &(G->h264enc1.venc1InArgs.roiParameters.listROI[0].bottomRight.x), (void *) 0 },
		{ "h264enc1", "listROI[0].bottomRight.y", DVEVM_ST_INT, &(G->h264enc1.venc1InArgs.roiParameters.listROI[0].bottomRight.y), (void *) 0 },
		{ "h264enc1", "roiType[0]", DVEVM_ST_INT, &(G->h264enc1.venc1InArgs.roiParameters.roiType[0]), (void *) FACE_OBJECT },
		{ "h264enc1", "roiPriority[0]", DVEVM_ST_INT, &(G->h264enc1.venc1InArgs.roiParameters.roiPriority[0]), (void *) 0 },
		{ "h264enc1", "listROI[1].topLeft.x", DVEVM_ST_INT, &(G->h264enc1.venc1InArgs.roiParameters.listROI[1].topLeft.x), (void *) 0 },
		{ "h264enc1", "listROI[1].topLeft.y", DVEVM_ST_INT, &(G->h264enc1.venc1InArgs.roiParameters.listROI[1].topLeft.y), (void *) 0 },
		{ "h264enc1", "listROI[1].bottomRight.x", DVEVM_ST_INT, &(G->h264enc1.venc1InArgs.roiParameters.listROI[1].bottomRight.x), (void *) 0 },
		{ "h264enc1", "listROI[1].bottomRight.y", DVEVM_ST_INT, &(G->h264enc1.venc1InArgs.roiParameters.listROI[1].bottomRight.y), (void *) 0 },
		{ "h264enc1", "roiType[1]", DVEVM_ST_INT, &(G->h264enc1.venc1InArgs.roiParameters.roiType[1]), (void *) FACE_OBJECT },
		{ "h264enc1", "roiPriority[1]", DVEVM_ST_INT, &(G->h264enc1.venc1InArgs.roiParameters.roiPriority[1]), (void *) 0 },
		{ "h264enc1", "listROI[2].topLeft.x", DVEVM_ST_INT, &(G->h264enc1.venc1InArgs.roiParameters.listROI[2].topLeft.x), (void *) 0 },
		{ "h264enc1", "listROI[2].topLeft.y", DVEVM_ST_INT, &(G->h264enc1.venc1InArgs.roiParameters.listROI[2].topLeft.y), (void *) 0 },
		{ "h264enc1", "listROI[2].bottomRight.x", DVEVM_ST_INT, &(G->h264enc1.venc1InArgs.roiParameters.listROI[2].bottomRight.x), (void *) 0 },
		{ "h264enc1", "listROI[2].bottomRight.y", DVEVM_ST_INT, &(G->h264enc1.venc1InArgs.roiParameters.listROI[2].bottomRight.y), (void *) 0 },
		{ "h264enc1", "roiType[2]", DVEVM_ST_INT, &(G->h264enc1.venc1InArgs.roiParameters.roiType[2]), (void *) FACE_OBJECT },
		{ "h264enc1", "roiPriority[2]", DVEVM_ST_INT, &(G->h264enc1.venc1InArgs.roiParameters.roiPriority[2]), (void *) 0 },
		{ "h264enc1", "listROI[3].topLeft.x", DVEVM_ST_INT, &(G->h264enc1.venc1InArgs.roiParameters.listROI[3].topLeft.x), (void *) 0 },
		{ "h264enc1", "listROI[3].topLeft.y", DVEVM_ST_INT, &(G->h264enc1.venc1InArgs.roiParameters.listROI[3].topLeft.y), (void *) 0 },
		{ "h264enc1", "listROI[3].bottomRight.x", DVEVM_ST_INT, &(G->h264enc1.venc1InArgs.roiParameters.listROI[3].bottomRight.x), (void *) 0 },
		{ "h264enc1", "listROI[3].bottomRight.y", DVEVM_ST_INT, &(G->h264enc1.venc1InArgs.roiParameters.listROI[3].bottomRight.y), (void *) 0 },
		{ "h264enc1", "roiType[3]", DVEVM_ST_INT, &(G->h264enc1.venc1InArgs.roiParameters.roiType[3]), (void *) FACE_OBJECT },
		{ "h264enc1", "roiPriority[3]", DVEVM_ST_INT, &(G->h264enc1.venc1InArgs.roiParameters.roiPriority[3]), (void *) 0 },
		{ "h264enc1", "listROI[4].topLeft.x", DVEVM_ST_INT, &(G->h264enc1.venc1InArgs.roiParameters.listROI[4].topLeft.x), (void *) 0 },
		{ "h264enc1", "listROI[4].topLeft.y", DVEVM_ST_INT, &(G->h264enc1.venc1InArgs.roiParameters.listROI[4].topLeft.y), (void *) 0 },
		{ "h264enc1", "listROI[4].bottomRight.x", DVEVM_ST_INT, &(G->h264enc1.venc1InArgs.roiParameters.listROI[4].bottomRight.x), (void *) 0 },
		{ "h264enc1", "listROI[4].bottomRight.y", DVEVM_ST_INT, &(G->h264enc1.venc1InArgs.roiParameters.listROI[4].bottomRight.y), (void *) 0 },
		{ "h264enc1", "roiType[4]", DVEVM_ST_INT, &(G->h264enc1.venc1InArgs.roiParameters.roiType[4]), (void *) FACE_OBJECT },
		{ "h264enc1", "roiPriority[4]", DVEVM_ST_INT, &(G->h264enc1.venc1InArgs.roiParameters.roiPriority[4]), (void *) 0 },
	
		/* Parameters for xdm 1.0 MPEG2 Encoder */
		{ "mpeg2enc1", "codec", DVEVM_ST_STR, G->mpeg2enc1.mpeg2enc1Name, "mpeg2enc1" },
		{ "mpeg2enc1", "encodingPreset", DVEVM_ST_INT, &(G->mpeg2enc1.venc1Params.videncParams.encodingPreset), (void *) 3 },
		{ "mpeg2enc1", "rateControlPreset", DVEVM_ST_INT, &(G->mpeg2enc1.venc1Params.videncParams.rateControlPreset), (void *) XDM_DEFAULT },
		{ "mpeg2enc1", "maxHeight", DVEVM_ST_INT, &(G->mpeg2enc1.venc1Params.videncParams.maxHeight), (void *) VIDENC1_MAX_HT },
		{ "mpeg2enc1", "maxWidth", DVEVM_ST_INT, &(G->mpeg2enc1.venc1Params.videncParams.maxWidth), (void *) VIDENC1_MAX_WD },
		{ "mpeg2enc1", "maxFrameRate", DVEVM_ST_INT, &(G->mpeg2enc1.venc1Params.videncParams.maxFrameRate), (void *) VIDENC1_MAX_FR },
		{ "mpeg2enc1", "maxBitRate", DVEVM_ST_INT, &(G->mpeg2enc1.venc1Params.videncParams.maxBitRate), (void *) VIDENC1_MAX_BR },
		{ "mpeg2enc1", "dataEndianness", DVEVM_ST_INT, &(G->mpeg2enc1.venc1Params.videncParams.dataEndianness), (void *) XDM_BYTE },
		{ "mpeg2enc1", "maxInterFrameInterval", DVEVM_ST_INT, &(G->mpeg2enc1.venc1Params.videncParams.maxInterFrameInterval), (void *) XDM_DEFAULT },
		{ "mpeg2enc1", "inputChromaFormat", DVEVM_ST_INT, &(G->mpeg2enc1.venc1Params.videncParams.inputChromaFormat), (void *) XDM_YUV_420SP },
		{ "mpeg2enc1", "inputContentType", DVEVM_ST_INT, &(G->mpeg2enc1.venc1Params.videncParams.inputContentType), (void *) XDM_DEFAULT },
		{ "mpeg2enc1", "reconChromaFormat", DVEVM_ST_INT, &(G->mpeg2enc1.venc1Params.videncParams.reconChromaFormat), (void *) XDM_YUV_420SP },

		{ "mpeg2enc1", "inputHeight", DVEVM_ST_INT, &(G->mpeg2enc1.venc1DynParams.videncDynamicParams.inputHeight), (void *) VIDENC1_MAX_HT },
		{ "mpeg2enc1", "inputWidth", DVEVM_ST_INT, &(G->mpeg2enc1.venc1DynParams.videncDynamicParams.inputWidth), (void *) VIDENC1_MAX_WD },
		{ "mpeg2enc1", "refFrameRate", DVEVM_ST_INT, &(G->mpeg2enc1.venc1DynParams.videncDynamicParams.refFrameRate), (void *) VIDENC1_MAX_FR },
		{ "mpeg2enc1", "targetFrameRate", DVEVM_ST_INT, &(G->mpeg2enc1.venc1DynParams.videncDynamicParams.targetFrameRate), (void *) VIDENC1_MAX_FR },
		{ "mpeg2enc1", "targetBitRate", DVEVM_ST_INT, &(G->mpeg2enc1.venc1DynParams.videncDynamicParams.targetBitRate), (void *) VIDENC1_MAX_BR },
		{ "mpeg2enc1", "intraFrameInterval", DVEVM_ST_INT, &(G->mpeg2enc1.venc1DynParams.videncDynamicParams.intraFrameInterval), (void *) VIDENC1_INTRA_FI },
		{ "mpeg2enc1", "generateHeader", DVEVM_ST_INT, &(G->mpeg2enc1.venc1DynParams.videncDynamicParams.generateHeader), (void *) XDM_DECODE_AU },
		{ "mpeg2enc1", "captureWidth", DVEVM_ST_INT, &(G->mpeg2enc1.venc1DynParams.videncDynamicParams.captureWidth), (void *) 0 },
		{ "mpeg2enc1", "forceFrame", DVEVM_ST_INT, &(G->mpeg2enc1.venc1DynParams.videncDynamicParams.forceFrame), (void *) 0 },
		{ "mpeg2enc1", "interFrameInterval", DVEVM_ST_INT, &(G->mpeg2enc1.venc1DynParams.videncDynamicParams.interFrameInterval), (void *) 0 },
		{ "mpeg2enc1", "mbDataFlag", DVEVM_ST_INT, &(G->mpeg2enc1.venc1DynParams.videncDynamicParams.mbDataFlag), (void *) 0 },

		{ "mpeg2enc1", "aspectRatio", DVEVM_ST_INT, &(G->mpeg2enc1.venc1Params.aspectRatio), (void *) 1 },
		{ "mpeg2enc1", "pixelRange", DVEVM_ST_INT, &(G->mpeg2enc1.venc1Params.pixelRange), (void *) 1},
		{ "mpeg2enc1", "timerResolution", DVEVM_ST_INT, &(G->mpeg2enc1.venc1Params.timerResolution), (void *) 60 },
		{ "mpeg2enc1", "ME_Type", DVEVM_ST_INT, &(G->mpeg2enc1.venc1Params.ME_Type), (void *) 1},
		{ "mpeg2enc1", "QscaleType", DVEVM_ST_INT, &(G->mpeg2enc1.venc1Params.QscaleType), (void *) 0},
		{ "mpeg2enc1", "IntraDCPrec", DVEVM_ST_INT, &(G->mpeg2enc1.venc1Params.IntraDCPrec), (void *) 0},
		{ "mpeg2enc1", "qpIntra", DVEVM_ST_INT, &(G->mpeg2enc1.venc1DynParams.qpIntra), (void *) 8 },
		{ "mpeg2enc1", "qpInter", DVEVM_ST_INT, &(G->mpeg2enc1.venc1DynParams.qpInter), (void *) 8 },
		{ "mpeg2enc1", "RcAlgo", DVEVM_ST_INT, &(G->mpeg2enc1.venc1DynParams.RcAlgo), (void *) IMP2VENC_RC_DEFAULT },
		{ "mpeg2enc1", "QPMax", DVEVM_ST_INT, &(G->mpeg2enc1.venc1DynParams.QPMax), (void *) 31 },
		{ "mpeg2enc1", "QPMin", DVEVM_ST_INT, &(G->mpeg2enc1.venc1DynParams.QPMin), (void *) 1 },
		{ "mpeg2enc1", "maxDelay", DVEVM_ST_INT, &(G->mpeg2enc1.venc1DynParams.maxDelay), (void *) 1000 },
		{ "mpeg2enc1", "qpInit", DVEVM_ST_INT, &(G->mpeg2enc1.venc1DynParams.qpInit), (void *) 8 },
		{ "mpeg2enc1", "PerceptualRC", DVEVM_ST_INT, &(G->mpeg2enc1.venc1DynParams.PerceptualRC), (void *) 0 },
		{ "mpeg2enc1", "reset_vIMCOP_every_frame", DVEVM_ST_INT, &(G->mpeg2enc1.venc1DynParams.reset_vIMCOP_every_frame), (void *) 1 },
		{ "mpeg2enc1", "mvSADoutFlag", DVEVM_ST_INT, &(G->mpeg2enc1.venc1DynParams.mvSADoutFlag), (void *) 0 },
		{ "mpeg2enc1", "numFrames", DVEVM_ST_INT, &(G->mpeg2enc1.numFrames), (void *) DEF_CAP_FRAMES },

		/* Parameters for xdm 1.0 MPEG4 Encoder */
		{ "mpeg4enc1", "codec", DVEVM_ST_STR, G->mpeg4enc1.mpeg4enc1Name, "mpeg4enc1" },
		{ "mpeg4enc1", "encodingPreset", DVEVM_ST_INT, &(G->mpeg4enc1.venc1Params.videncParams.encodingPreset), (void *) 3 },
		{ "mpeg4enc1", "rateControlPreset", DVEVM_ST_INT, &(G->mpeg4enc1.venc1Params.videncParams.rateControlPreset), (void *) XDM_DEFAULT },
		{ "mpeg4enc1", "maxHeight", DVEVM_ST_INT, &(G->mpeg4enc1.venc1Params.videncParams.maxHeight), (void *) VIDENC1_MAX_HT },
		{ "mpeg4enc1", "maxWidth", DVEVM_ST_INT, &(G->mpeg4enc1.venc1Params.videncParams.maxWidth), (void *) VIDENC1_MAX_WD },
		{ "mpeg4enc1", "maxFrameRate", DVEVM_ST_INT, &(G->mpeg4enc1.venc1Params.videncParams.maxFrameRate), (void *) VIDENC1_MAX_FR },
		{ "mpeg4enc1", "maxBitRate", DVEVM_ST_INT, &(G->mpeg4enc1.venc1Params.videncParams.maxBitRate), (void *) VIDENC1_MAX_BR },
		{ "mpeg4enc1", "dataEndianness", DVEVM_ST_INT, &(G->mpeg4enc1.venc1Params.videncParams.dataEndianness), (void *) XDM_BYTE },
		{ "mpeg4enc1", "maxInterFrameInterval", DVEVM_ST_INT, &(G->mpeg4enc1.venc1Params.videncParams.maxInterFrameInterval), (void *) XDM_DEFAULT },
		{ "mpeg4enc1", "inputChromaFormat", DVEVM_ST_INT, &(G->mpeg4enc1.venc1Params.videncParams.inputChromaFormat), (void *) XDM_YUV_420SP },
		{ "mpeg4enc1", "inputContentType", DVEVM_ST_INT, &(G->mpeg4enc1.venc1Params.videncParams.inputContentType), (void *) XDM_DEFAULT },
		{ "mpeg4enc1", "reconChromaFormat", DVEVM_ST_INT, &(G->mpeg4enc1.venc1Params.videncParams.reconChromaFormat), (void *) XDM_YUV_420SP },

		{ "mpeg4enc1", "inputHeight", DVEVM_ST_INT, &(G->mpeg4enc1.venc1DynParams.videncDynamicParams.inputHeight), (void *) VIDENC1_MAX_HT },
		{ "mpeg4enc1", "inputWidth", DVEVM_ST_INT, &(G->mpeg4enc1.venc1DynParams.videncDynamicParams.inputWidth), (void *) VIDENC1_MAX_WD },
		{ "mpeg4enc1", "refFrameRate", DVEVM_ST_INT, &(G->mpeg4enc1.venc1DynParams.videncDynamicParams.refFrameRate), (void *) VIDENC1_MAX_FR },
		{ "mpeg4enc1", "targetFrameRate", DVEVM_ST_INT, &(G->mpeg4enc1.venc1DynParams.videncDynamicParams.targetFrameRate), (void *) VIDENC1_MAX_FR },
		{ "mpeg4enc1", "targetBitRate", DVEVM_ST_INT, &(G->mpeg4enc1.venc1DynParams.videncDynamicParams.targetBitRate), (void *) VIDENC1_MAX_BR },
		{ "mpeg4enc1", "intraFrameInterval", DVEVM_ST_INT, &(G->mpeg4enc1.venc1DynParams.videncDynamicParams.intraFrameInterval), (void *) VIDENC1_INTRA_FI },
		{ "mpeg4enc1", "generateHeader", DVEVM_ST_INT, &(G->mpeg4enc1.venc1DynParams.videncDynamicParams.generateHeader), (void *) XDM_DECODE_AU },
		{ "mpeg4enc1", "captureWidth", DVEVM_ST_INT, &(G->mpeg4enc1.venc1DynParams.videncDynamicParams.captureWidth), (void *) 0 },
		{ "mpeg4enc1", "forceFrame", DVEVM_ST_INT, &(G->mpeg4enc1.venc1DynParams.videncDynamicParams.forceFrame), (void *) 0 },
		{ "mpeg4enc1", "interFrameInterval", DVEVM_ST_INT, &(G->mpeg4enc1.venc1DynParams.videncDynamicParams.interFrameInterval), (void *) 0 },
		{ "mpeg4enc1", "mbDataFlag", DVEVM_ST_INT, &(G->mpeg4enc1.venc1DynParams.videncDynamicParams.mbDataFlag), (void *) 0 },

		{ "mpeg4enc1", "extsubWindowHeight", DVEVM_ST_INT, &(G->mpeg4enc1.venc1Params.subWindowHeight), (void *) VIDENC1_MAX_HT },
		{ "mpeg4enc1", "extsubWindowWidth", DVEVM_ST_INT, &(G->mpeg4enc1.venc1Params.subWindowWidth), (void *) VIDENC1_MAX_WD },
		{ "mpeg4enc1", "extrotation", DVEVM_ST_INT, &(G->mpeg4enc1.venc1Params.rotation), (void *)  0 },
		{ "mpeg4enc1", "extvbvSize", DVEVM_ST_INT, &(G->mpeg4enc1.venc1Params.vbvSize), (void *)  0 },
		{ "mpeg4enc1", "extsvhMode", DVEVM_ST_INT, &(G->mpeg4enc1.venc1Params.svhMode), (void *) 0 },
		{ "mpeg4enc1", "extIFrameBitRateBiasFactor", DVEVM_ST_INT, &(G->mpeg4enc1.venc1Params.IFrameBitRateBiasFactor), (void *) 256 },
		{ "mpeg4enc1", "extPFrameBitRateBiasFactor", DVEVM_ST_INT, &(G->mpeg4enc1.venc1Params.PFrameBitRateBiasFactor), (void *) 256 },
		{ "mpeg4enc1", "extpeakBufWindow", DVEVM_ST_INT, &(G->mpeg4enc1.venc1Params.peakBufWindow), (void *) 2 },
		{ "mpeg4enc1", "extminBitRate", DVEVM_ST_INT, &(G->mpeg4enc1.venc1Params.minBitRate), (void *) VIDENC1_MAX_BR },
		{ "mpeg4enc1", "extintraAlgo", DVEVM_ST_INT, &(G->mpeg4enc1.venc1DynParams.intraAlgo), (void *)  IMP4VENC_INTRA_INTER_DECISION_LQ_HP},
		{ "mpeg4enc1", "extnumMBRows", DVEVM_ST_INT, &(G->mpeg4enc1.venc1DynParams.numMBRows), (void *) 1 },
		{ "mpeg4enc1", "extinitQ", DVEVM_ST_INT, &(G->mpeg4enc1.venc1DynParams.initQ), (void *) 0 },
		{ "mpeg4enc1", "extrcQMax", DVEVM_ST_INT, &(G->mpeg4enc1.venc1DynParams.rcQMax), (void *) 31 },
		{ "mpeg4enc1", "extrcQMin", DVEVM_ST_INT, &(G->mpeg4enc1.venc1DynParams.rcQMin), (void *) 1 },
		{ "mpeg4enc1", "extintraFrameQP", DVEVM_ST_INT, &(G->mpeg4enc1.venc1DynParams.intraFrameQP), (void *) 0 },
		{ "mpeg4enc1", "extinterFrameQP", DVEVM_ST_INT, &(G->mpeg4enc1.venc1DynParams.interFrameQP), (void *) 0 },
		{ "mpeg4enc1", "extrateFix", DVEVM_ST_INT, &(G->mpeg4enc1.venc1DynParams.rateFix), (void *) 0 },
		{ "mpeg4enc1", "extrateFixRange", DVEVM_ST_INT, &(G->mpeg4enc1.venc1DynParams.rateFixRange), (void *) 0 },
		{ "mpeg4enc1", "extmeAlgo", DVEVM_ST_INT, &(G->mpeg4enc1.venc1DynParams.meAlgo), (void *) IMP4VENC_ME_MQ_MP },
		{ "mpeg4enc1", "extskipMBAlgo", DVEVM_ST_INT, &(G->mpeg4enc1.venc1DynParams.skipMBAlgo), (void *) IMP4VENC_SKIP_MB_LQ_HP },
		{ "mpeg4enc1", "extunrestrictedMV", DVEVM_ST_INT, &(G->mpeg4enc1.venc1DynParams.unrestrictedMV), (void *) IMP4VENC_UMV_LQ_HP },
		{ "mpeg4enc1", "extmvDataEnable", DVEVM_ST_INT, &(G->mpeg4enc1.venc1DynParams.mvDataEnable), (void *) 0 },
		{ "mpeg4enc1", "numFrames", DVEVM_ST_INT, &(G->mpeg4enc1.numFrames), (void *) DEF_CAP_FRAMES }, 

		/* Parameters for xdm 1.0 MPEG4 HDVICP Encoder */
		{ "mpeg4hdvicpenc1", "codec", DVEVM_ST_STR, G->mpeg4hdvicpenc1.mpeg4enc1Name, "mpeg4hdvicpenc1" },
		{ "mpeg4hdvicpenc1", "encodingPreset", DVEVM_ST_INT, &(G->mpeg4hdvicpenc1.venc1Params.videncParams.encodingPreset), (void *) 3 },
		{ "mpeg4hdvicpenc1", "rateControlPreset", DVEVM_ST_INT, &(G->mpeg4hdvicpenc1.venc1Params.videncParams.rateControlPreset), (void *) XDM_DEFAULT },
		{ "mpeg4hdvicpenc1", "maxHeight", DVEVM_ST_INT, &(G->mpeg4hdvicpenc1.venc1Params.videncParams.maxHeight), (void *) VIDENC1_MAX_HT },
		{ "mpeg4hdvicpenc1", "maxWidth", DVEVM_ST_INT, &(G->mpeg4hdvicpenc1.venc1Params.videncParams.maxWidth), (void *) VIDENC1_MAX_WD },
		{ "mpeg4hdvicpenc1", "maxFrameRate", DVEVM_ST_INT, &(G->mpeg4hdvicpenc1.venc1Params.videncParams.maxFrameRate), (void *) VIDENC1_MAX_FR },
		{ "mpeg4hdvicpenc1", "maxBitRate", DVEVM_ST_INT, &(G->mpeg4hdvicpenc1.venc1Params.videncParams.maxBitRate), (void *) VIDENC1_MAX_BR },
		{ "mpeg4hdvicpenc1", "dataEndianness", DVEVM_ST_INT, &(G->mpeg4hdvicpenc1.venc1Params.videncParams.dataEndianness), (void *) XDM_BYTE },
		{ "mpeg4hdvicpenc1", "maxInterFrameInterval", DVEVM_ST_INT, &(G->mpeg4hdvicpenc1.venc1Params.videncParams.maxInterFrameInterval), (void *) XDM_DEFAULT },
		{ "mpeg4hdvicpenc1", "inputChromaFormat", DVEVM_ST_INT, &(G->mpeg4hdvicpenc1.venc1Params.videncParams.inputChromaFormat), (void *) XDM_YUV_420SP },
		{ "mpeg4hdvicpenc1", "inputContentType", DVEVM_ST_INT, &(G->mpeg4hdvicpenc1.venc1Params.videncParams.inputContentType), (void *) XDM_DEFAULT },
		{ "mpeg4hdvicpenc1", "reconChromaFormat", DVEVM_ST_INT, &(G->mpeg4hdvicpenc1.venc1Params.videncParams.reconChromaFormat), (void *) XDM_YUV_420SP },

		{ "mpeg4hdvicpenc1", "inputHeight", DVEVM_ST_INT, &(G->mpeg4hdvicpenc1.venc1DynParams.videncDynamicParams.inputHeight), (void *) VIDENC1_MAX_HT },
		{ "mpeg4hdvicpenc1", "inputWidth", DVEVM_ST_INT, &(G->mpeg4hdvicpenc1.venc1DynParams.videncDynamicParams.inputWidth), (void *) VIDENC1_MAX_WD },
		{ "mpeg4hdvicpenc1", "refFrameRate", DVEVM_ST_INT, &(G->mpeg4hdvicpenc1.venc1DynParams.videncDynamicParams.refFrameRate), (void *) VIDENC1_MAX_FR },
		{ "mpeg4hdvicpenc1", "targetFrameRate", DVEVM_ST_INT, &(G->mpeg4hdvicpenc1.venc1DynParams.videncDynamicParams.targetFrameRate), (void *) VIDENC1_MAX_FR },
		{ "mpeg4hdvicpenc1", "targetBitRate", DVEVM_ST_INT, &(G->mpeg4hdvicpenc1.venc1DynParams.videncDynamicParams.targetBitRate), (void *) VIDENC1_MAX_BR },
		{ "mpeg4hdvicpenc1", "intraFrameInterval", DVEVM_ST_INT, &(G->mpeg4hdvicpenc1.venc1DynParams.videncDynamicParams.intraFrameInterval), (void *) VIDENC1_INTRA_FI },
		{ "mpeg4hdvicpenc1", "generateHeader", DVEVM_ST_INT, &(G->mpeg4hdvicpenc1.venc1DynParams.videncDynamicParams.generateHeader), (void *) XDM_DECODE_AU },
		{ "mpeg4hdvicpenc1", "captureWidth", DVEVM_ST_INT, &(G->mpeg4hdvicpenc1.venc1DynParams.videncDynamicParams.captureWidth), (void *) 0 },
		{ "mpeg4hdvicpenc1", "forceFrame", DVEVM_ST_INT, &(G->mpeg4hdvicpenc1.venc1DynParams.videncDynamicParams.forceFrame), (void *) 0 },
		{ "mpeg4hdvicpenc1", "interFrameInterval", DVEVM_ST_INT, &(G->mpeg4hdvicpenc1.venc1DynParams.videncDynamicParams.interFrameInterval), (void *) 0 },
		{ "mpeg4hdvicpenc1", "mbDataFlag", DVEVM_ST_INT, &(G->mpeg4hdvicpenc1.venc1DynParams.videncDynamicParams.mbDataFlag), (void *) 0 },

		{ "mpeg4hdvicpenc1", "extMPEG4_mode", DVEVM_ST_INT, &(G->mpeg4hdvicpenc1.venc1Params.MPEG4_mode), (void *) 1 },
		{ "mpeg4hdvicpenc1", "extlevelIdc", DVEVM_ST_INT, &(G->mpeg4hdvicpenc1.venc1Params.levelIdc), (void *) IMP4HDVICPENC_SP_LEVEL_5},
		{ "mpeg4hdvicpenc1", "extuseVOS", DVEVM_ST_INT, &(G->mpeg4hdvicpenc1.venc1Params.useVOS), (void *) 1 },
		{ "mpeg4hdvicpenc1", "extuseGOV", DVEVM_ST_INT, &(G->mpeg4hdvicpenc1.venc1Params.useGOV), (void *) 0},
		{ "mpeg4hdvicpenc1", "extuseDataPartition", DVEVM_ST_INT, &(G->mpeg4hdvicpenc1.venc1Params.useDataPartition), (void *) 0},
		{ "mpeg4hdvicpenc1", "extuseRVLC", DVEVM_ST_INT, &(G->mpeg4hdvicpenc1.venc1Params.useRVLC), (void *) 0},
		{ "mpeg4hdvicpenc1", "extaspectRatio", DVEVM_ST_INT, &(G->mpeg4hdvicpenc1.venc1Params.aspectRatio), (void *) IMP4HDVICPENC_AR_DEFAULT},
		{ "mpeg4hdvicpenc1", "extpixelRange", DVEVM_ST_INT, &(G->mpeg4hdvicpenc1.venc1Params.pixelRange), (void *) IMP4HDVICPENC_PR_DEFAULT },
		{ "mpeg4hdvicpenc1", "exttimerResolution", DVEVM_ST_INT, &(G->mpeg4hdvicpenc1.venc1Params.timerResolution), (void *) 30000 },
		{ "mpeg4hdvicpenc1", "extME_Type", DVEVM_ST_INT, &(G->mpeg4hdvicpenc1.venc1Params.ME_Type), (void *) 0 },
		{ "mpeg4hdvicpenc1", "extUMV", DVEVM_ST_INT, &(G->mpeg4hdvicpenc1.venc1Params.UMV), (void *) 1 },
		{ "mpeg4hdvicpenc1", "extEncQuality_mode", DVEVM_ST_INT, &(G->mpeg4hdvicpenc1.venc1Params.EncQuality_mode), (void *) 0 },
		{ "mpeg4hdvicpenc1", "extFour_MV_mode", DVEVM_ST_INT, &(G->mpeg4hdvicpenc1.venc1DynParams.Four_MV_mode), (void *) 0 },
		{ "mpeg4hdvicpenc1", "extPacketSize", DVEVM_ST_INT, &(G->mpeg4hdvicpenc1.venc1DynParams.PacketSize), (void *) 0 },
		{ "mpeg4hdvicpenc1", "extqpIntra", DVEVM_ST_INT, &(G->mpeg4hdvicpenc1.venc1DynParams.qpIntra), (void *) 8 },
		{ "mpeg4hdvicpenc1", "extqpInter", DVEVM_ST_INT, &(G->mpeg4hdvicpenc1.venc1DynParams.qpInter), (void *) 8 },
		{ "mpeg4hdvicpenc1", "extairRate", DVEVM_ST_INT, &(G->mpeg4hdvicpenc1.venc1DynParams.airRate), (void *) 0 },
		{ "mpeg4hdvicpenc1", "extuseHEC", DVEVM_ST_INT, &(G->mpeg4hdvicpenc1.venc1DynParams.useHEC), (void *) 0 },
		{ "mpeg4hdvicpenc1", "extuseGOBSync", DVEVM_ST_INT, &(G->mpeg4hdvicpenc1.venc1DynParams.useGOBSync), (void *) 0 },
		{ "mpeg4hdvicpenc1", "extRcAlgo", DVEVM_ST_INT, &(G->mpeg4hdvicpenc1.venc1DynParams.RcAlgo), (void *) IMP4HDVICPENC_RC_DEFAULT },
		{ "mpeg4hdvicpenc1", "extQPMax", DVEVM_ST_INT, &(G->mpeg4hdvicpenc1.venc1DynParams.QPMax), (void *) 31 },
		{ "mpeg4hdvicpenc1", "extQPMin", DVEVM_ST_INT, &(G->mpeg4hdvicpenc1.venc1DynParams.QPMin), (void *) 2 },
		{ "mpeg4hdvicpenc1", "extmaxDelay", DVEVM_ST_INT, &(G->mpeg4hdvicpenc1.venc1DynParams.maxDelay), (void *) 1000 },
		{ "mpeg4hdvicpenc1", "extqpInit", DVEVM_ST_INT, &(G->mpeg4hdvicpenc1.venc1DynParams.qpInit), (void *) 8 },
		{ "mpeg4hdvicpenc1", "extPerceptualRC", DVEVM_ST_INT, &(G->mpeg4hdvicpenc1.venc1DynParams.PerceptualRC), (void *) 0 },
		{ "mpeg4hdvicpenc1", "extreset_vIMCOP_every_frame", DVEVM_ST_INT, &(G->mpeg4hdvicpenc1.venc1DynParams.reset_vIMCOP_every_frame), (void *) 1 },
		{ "mpeg4hdvicpenc1", "extmvSADoutFlag", DVEVM_ST_INT, &(G->mpeg4hdvicpenc1.venc1DynParams.mvSADoutFlag), (void *) 0 },
		{ "mpeg4hdvicpenc1", "numFrames", DVEVM_ST_INT, &(G->mpeg4hdvicpenc1.numFrames), (void *) DEF_CAP_FRAMES }, 

		/* Parameters for AACHE Decoder 1.0 */
		{ "aachedec1", "codec", DVEVM_ST_STR, G->aachedec1.adecName, "aacdec1" },
		{ "aachedec1", "outputPCMWidth", DVEVM_ST_INT, &(G->aachedec1.adecParams.auddec_params.outputPCMWidth), (void *) 16 },
		{ "aachedec1", "pcmFormat", DVEVM_ST_INT, &(G->aachedec1.adecParams.auddec_params.pcmFormat), (void *) IAUDIO_INTERLEAVED },
		{ "aachedec1", "dataEndianness", DVEVM_ST_INT, &(G->aachedec1.adecParams.auddec_params.dataEndianness), (void *) XDM_LE_16 },
		{ "aachedec1", "desiredChannelMode", DVEVM_ST_INT, &(G->aachedec1.desiredChannelMode), (void *) IAUDIO_2_0 },
		{ "aachedec1", "downSampleSbrFlag", DVEVM_ST_INT, &(G->aachedec1.adecDynParams.auddec_dynamicparams.downSampleSbrFlag), (void *) 0 },
		{ "aachedec1", "i_max_channels", DVEVM_ST_INT, &(G->aachedec1.adecParams.i_max_channels), (void *) 2},
		{ "aachedec1", "i_flag_08khz_out", DVEVM_ST_INT, &(G->aachedec1.adecParams.i_flag_08khz_out), (void *) 0},
		{ "aachedec1", "i_flag_16khz_out", DVEVM_ST_INT, &(G->aachedec1.adecParams.i_flag_16khz_out), (void *) 0},
		{ "aachedec1", "i_interleave", DVEVM_ST_INT, &(G->aachedec1.adecParams.i_interleave), (void *) 1},
		{ "aachedec1", "i_mp4_flag", DVEVM_ST_INT, &(G->aachedec1.adecParams.i_mp4_flag), (void *) 0},
		{ "aachedec1", "i_disable_sync", DVEVM_ST_INT, &(G->aachedec1.adecParams.i_disable_sync), (void *) 0},
		{ "aachedec1", "i_auto_sbr_upsample", DVEVM_ST_INT, &(G->aachedec1.adecParams.i_auto_sbr_upsample), (void *) 1},
		{ "aachedec1", "i_sampfreq", DVEVM_ST_INT, &(G->aachedec1.adecParams.i_sampfreq), (void *) 0},
		{ "aachedec1", "i_coupling_channel", DVEVM_ST_INT, &(G->aachedec1.adecParams.i_coupling_channel), (void *) 0},
		{ "aachedec1", "inbufsize", DVEVM_ST_INT, &(G->aachedec1.inBuf.bufSizes[0]), (void *) 10000 },
		{ "aachedec1", "outbufsize", DVEVM_ST_INT, &(G->aachedec1.outBuf.bufSizes[0]), (void *) 16384 },

		/* Parameters for AAC HE Encoder XDM 1.0 Extended Params*/
		{ "aaclcenc1", "codec", DVEVM_ST_STR, G->aacheenc1.aacenc1Name, "aaclcenc1" },
		{ "aaclcenc1", "seconds", DVEVM_ST_INT, &(G->aacheenc1.seconds), (void *) DEFAULT_AACHEENC1_TIME },
		{ "aaclcenc1", "sampleRate", DVEVM_ST_INT, &(G->aacheenc1.aacenc1Params.audenc_params.sampleRate), (void *) 44100 },
		{ "aaclcenc1", "bitRate", DVEVM_ST_INT, &(G->aacheenc1.aacenc1Params.audenc_params.bitRate), (void *) 64000 },
		{ "aaclcenc1", "channelMode", DVEVM_ST_INT, &(G->aacheenc1.aacenc1Params.audenc_params.channelMode), (void *) (XDAS_Int32)(IAUDIO_2_0) },
		{ "aaclcenc1", "dataEndianness", DVEVM_ST_INT, &(G->aacheenc1.aacenc1Params.audenc_params.dataEndianness), (void *) (XDAS_Int32)(XDM_LE_16) },
		{ "aaclcenc1", "encMode", DVEVM_ST_INT, &(G->aacheenc1.aacenc1Params.audenc_params.encMode), (void *) (XDAS_Int32)(IAUDIO_CBR) },
		{ "aaclcenc1", "inputFormat", DVEVM_ST_INT, &(G->aacheenc1.aacenc1Params.audenc_params.inputFormat), (void *) (XDAS_Int32)(IAUDIO_INTERLEAVED) },
		{ "aaclcenc1", "inputBitsPerSample", DVEVM_ST_INT, &(G->aacheenc1.aacenc1Params.audenc_params.inputBitsPerSample), (void *) 16 },
		{ "aaclcenc1", "maxBitRate", DVEVM_ST_INT, &(G->aacheenc1.aacenc1Params.audenc_params.maxBitRate), (void *) 144000 },
		{ "aaclcenc1", "dualMonoMode", DVEVM_ST_INT, &(G->aacheenc1.aacenc1Params.audenc_params.dualMonoMode), (void *) (XDAS_Int32) IAUDIO_DUALMONO_LR },
		{ "aaclcenc1", "crcFlag", DVEVM_ST_INT, &(G->aacheenc1.aacenc1Params.audenc_params.crcFlag), (void *) XDAS_FALSE },
		{ "aaclcenc1", "ancFlag", DVEVM_ST_INT, &(G->aacheenc1.aacenc1Params.audenc_params.ancFlag), (void *) XDAS_FALSE },
		{ "aaclcenc1", "lfeFlag", DVEVM_ST_INT, &(G->aacheenc1.aacenc1Params.audenc_params.lfeFlag), (void *) XDAS_FALSE },
		{ "aaclcenc1", "noChannels", DVEVM_ST_INT, &(G->aacheenc1.aacenc1Params.noChannels), (void *) 2 },
		{ "aaclcenc1", "aacClassic", DVEVM_ST_INT, &(G->aacheenc1.aacenc1Params.aacClassic), (void *) 0 },
		{ "aaclcenc1", "psEnable", DVEVM_ST_INT, &(G->aacheenc1.aacenc1Params.psEnable), (void *) 0 },
		{ "aaclcenc1", "dualMono", DVEVM_ST_INT, &(G->aacheenc1.aacenc1Params.dualMono), (void *) 0 },
		{ "aaclcenc1", "downmix", DVEVM_ST_INT, &(G->aacheenc1.aacenc1Params.downmix), (void *) 0 },
		{ "aaclcenc1", "useSpeechConfig", DVEVM_ST_INT, &(G->aacheenc1.aacenc1Params.useSpeechConfig), (void *) 0 },
		{ "aaclcenc1", "fNoStereoPreprocessing", DVEVM_ST_INT, &(G->aacheenc1.aacenc1Params.fNoStereoPreprocessing), (void *) 0 },
		{ "aaclcenc1", "invQuant", DVEVM_ST_INT, &(G->aacheenc1.aacenc1Params.invQuant), (void *) 2 },
		{ "aaclcenc1", "useTns", DVEVM_ST_INT, &(G->aacheenc1.aacenc1Params.useTns), (void *) 1 },
		{ "aaclcenc1", "use_ADTS", DVEVM_ST_INT, &(G->aacheenc1.aacenc1Params.use_ADTS), (void *) 1 },
		{ "aaclcenc1", "use_ADIF", DVEVM_ST_INT, &(G->aacheenc1.aacenc1Params.use_ADIF), (void *) 0 },
		{ "aaclcenc1", "full_bandwidth", DVEVM_ST_INT, &(G->aacheenc1.aacenc1Params.full_bandwidth), (void *) 0 },
		{ "aaclcenc1", "i_channels_mask", DVEVM_ST_INT, &(G->aacheenc1.aacenc1Params.i_channels_mask), (void *) 0 },
		{ "aaclcenc1", "i_num_coupling_chan", DVEVM_ST_INT, &(G->aacheenc1.aacenc1Params.i_num_coupling_chan), (void *) 0 },
		{ "aaclcenc1", "write_program_config_element", DVEVM_ST_INT, &(G->aacheenc1.aacenc1Params.write_program_config_element), (void *) 0 },
		{ "aaclcenc1", "dynamicparams.sampleRate", DVEVM_ST_INT, &(G->aacheenc1.aacenc1DynParams.audenc_dynamicparams.sampleRate), (void *) 44100 },
		{ "aaclcenc1", "dynamicparams.bitRate", DVEVM_ST_INT, &(G->aacheenc1.aacenc1DynParams.audenc_dynamicparams.bitRate), (void *) 64000 },
		{ "aaclcenc1", "dynamicparams.channelMode", DVEVM_ST_INT, &(G->aacheenc1.aacenc1DynParams.audenc_dynamicparams.channelMode), (void *) IAUDIO_2_0 },
		{ "aaclcenc1", "dynamicparams.lfeFlag", DVEVM_ST_INT, &(G->aacheenc1.aacenc1DynParams.audenc_dynamicparams.lfeFlag), (void *) XDAS_FALSE },
		{ "aaclcenc1", "dynamicparams.dualMonoMode", DVEVM_ST_INT, &(G->aacheenc1.aacenc1DynParams.audenc_dynamicparams.dualMonoMode), (void *) IAUDIO_DUALMONO_LR },
		{ "aaclcenc1", "dynamicparams.inputBitsPerSample", DVEVM_ST_INT, &(G->aacheenc1.aacenc1DynParams.audenc_dynamicparams.inputBitsPerSample), (void *) 16 },
		/* Parameters for MP3 Decoder 1.0 */
		{ "mp3dec1", "codec", DVEVM_ST_STR, G->mp3dec1.adecName, "mp3dec1" },
		{ "mp3dec1", "outputPCMWidth", DVEVM_ST_INT, &(G->mp3dec1.adecParams.auddec_params.outputPCMWidth), (void *) 16 },
		{ "mp3dec1", "pcmFormat", DVEVM_ST_INT, &(G->mp3dec1.adecParams.auddec_params.pcmFormat), (void *) IAUDIO_INTERLEAVED },
		{ "mp3dec1", "dataEndianness", DVEVM_ST_INT, &(G->mp3dec1.adecParams.auddec_params.dataEndianness), (void *) XDM_LE_16 },
		{ "mp3dec1", "desiredChannelMode", DVEVM_ST_INT, &(G->mp3dec1.desiredChannelMode), (void *) IAUDIO_2_0 },
		{ "mp3dec1", "downSampleSbrFlag", DVEVM_ST_INT, &(G->mp3dec1.adecDynParams.auddec_dynamicparams.downSampleSbrFlag), (void *) 0 },
		{ "mp3dec1", "i_frame_synch_check", DVEVM_ST_INT, &(G->mp3dec1.adecParams.i_frame_synch_check), (void *) 1},
		{ "mp3dec1", "inbufsize", DVEVM_ST_INT, &(G->mp3dec1.inBuf.bufSizes[0]), (void *) 10000 },
		{ "mp3dec1", "outbufsize", DVEVM_ST_INT, &(G->mp3dec1.outBuf.bufSizes[0]), (void *) 16384 },

		/* Parameters for  MP3 Encoder XDM 1.0 Extended Params*/
		{ "mp3enc1", "codec", DVEVM_ST_STR, G->mp3enc1.aenc1Name, "mp3enc1" },
		{ "mp3enc1", "seconds", DVEVM_ST_INT, &(G->mp3enc1.seconds), (void *) DEFAULT_AACHEENC1_TIME },
		{ "mp3enc1", "sampleRate", DVEVM_ST_INT, &(G->mp3enc1.aenc1Params.audenc_params.sampleRate), (void *) 44100 },
		{ "mp3enc1", "bitRate", DVEVM_ST_INT, &(G->mp3enc1.aenc1Params.audenc_params.bitRate), (void *) 192000 },
		{ "mp3enc1", "channelMode", DVEVM_ST_INT, &(G->mp3enc1.aenc1Params.audenc_params.channelMode), (void *) (XDAS_Int32)(IAUDIO_2_0) },
		{ "mp3enc1", "dataEndianness", DVEVM_ST_INT, &(G->mp3enc1.aenc1Params.audenc_params.dataEndianness), (void *) (XDAS_Int32)(XDM_LE_16) },
		{ "mp3enc1", "encMode", DVEVM_ST_INT, &(G->mp3enc1.aenc1Params.audenc_params.encMode), (void *) (XDAS_Int32)(IAUDIO_CBR) },
		{ "mp3enc1", "inputFormat", DVEVM_ST_INT, &(G->mp3enc1.aenc1Params.audenc_params.inputFormat), (void *) (XDAS_Int32)(IAUDIO_INTERLEAVED) },
		{ "mp3enc1", "inputBitsPerSample", DVEVM_ST_INT, &(G->mp3enc1.aenc1Params.audenc_params.inputBitsPerSample), (void *) 16 },
		{ "mp3enc1", "maxBitRate", DVEVM_ST_INT, &(G->mp3enc1.aenc1Params.audenc_params.maxBitRate), (void *) 192000 },
		{ "mp3enc1", "dualMonoMode", DVEVM_ST_INT, &(G->mp3enc1.aenc1Params.audenc_params.dualMonoMode), (void *) (XDAS_Int32) IAUDIO_DUALMONO_LR },
		{ "mp3enc1", "crcFlag", DVEVM_ST_INT, &(G->mp3enc1.aenc1Params.audenc_params.crcFlag), (void *) XDAS_FALSE },
		{ "mp3enc1", "ancFlag", DVEVM_ST_INT, &(G->mp3enc1.aenc1Params.audenc_params.ancFlag), (void *) XDAS_FALSE },
		{ "mp3enc1", "lfeFlag", DVEVM_ST_INT, &(G->mp3enc1.aenc1Params.audenc_params.lfeFlag), (void *) XDAS_FALSE },
		{ "mp3enc1", "packet", DVEVM_ST_INT, &(G->mp3enc1.aenc1Params.packet), (void *) 0 },
		{ "mp3enc1", "dynamicparams.sampleRate", DVEVM_ST_INT, &(G->mp3enc1.aenc1DynParams.audenc_dynamicparams.sampleRate), (void *) 44100 },
		{ "mp3enc1", "dynamicparams.bitRate", DVEVM_ST_INT, &(G->mp3enc1.aenc1DynParams.audenc_dynamicparams.bitRate), (void *) 192000 },
		{ "mp3enc1", "dynamicparams.channelMode", DVEVM_ST_INT, &(G->mp3enc1.aenc1DynParams.audenc_dynamicparams.channelMode), (void *) IAUDIO_2_0 },
		{ "mp3enc1", "dynamicparams.lfeFlag", DVEVM_ST_INT, &(G->mp3enc1.aenc1DynParams.audenc_dynamicparams.lfeFlag), (void *) XDAS_FALSE },
		{ "mp3enc1", "dynamicparams.dualMonoMode", DVEVM_ST_INT, &(G->mp3enc1.aenc1DynParams.audenc_dynamicparams.dualMonoMode), (void *) IAUDIO_DUALMONO_LR },
		{ "mp3enc1", "dynamicparams.inputBitsPerSample", DVEVM_ST_INT, &(G->mp3enc1.aenc1DynParams.audenc_dynamicparams.inputBitsPerSample), (void *) 16 },

		/* Parameters for MP3 Decoder 1.0 */
		{ "wmadec1", "codec", DVEVM_ST_STR, G->wmadec1.adecName, "wmadec1" },
		{ "wmadec1", "outputPCMWidth", DVEVM_ST_INT, &(G->wmadec1.adecParams.auddec_params.outputPCMWidth), (void *) 16 },
		{ "wmadec1", "pcmFormat", DVEVM_ST_INT, &(G->wmadec1.adecParams.auddec_params.pcmFormat), (void *) IAUDIO_INTERLEAVED },
		{ "wmadec1", "dataEndianness", DVEVM_ST_INT, &(G->wmadec1.adecParams.auddec_params.dataEndianness), (void *) XDM_LE_16 },
		{ "wmadec1", "desiredChannelMode", DVEVM_ST_INT, &(G->wmadec1.desiredChannelMode), (void *) -1 },
		{ "wmadec1", "lfeFlag", DVEVM_ST_INT, &(G->wmadec1.lfeFlag), (void *) -1 },
		{ "wmadec1", "downSampleSbrFlag", DVEVM_ST_INT, &(G->wmadec1.adecDynParams.auddec_dynamicparams.downSampleSbrFlag), (void *) 0 },
		{ "wmadec1", "i_constant_output", DVEVM_ST_INT, &(G->wmadec1.adecParams.i_constant_output), (void *) 0},
		{ "wmadec1", "i_use_full_output_buff", DVEVM_ST_INT, &(G->wmadec1.adecParams.i_use_full_output_buff), (void *) 1},
		{ "wmadec1", "inbufsize", DVEVM_ST_INT, &(G->wmadec1.inBuf.bufSizes[0]), (void *) 10000 },
		{ "wmadec1", "outbufsize", DVEVM_ST_INT, &(G->wmadec1.outBuf.bufSizes[0]), (void *) 16384 },

		/* Parameters for  MP3 Encoder XDM 1.0 Extended Params*/
		{ "wmaenc1", "codec", DVEVM_ST_STR, G->wmaenc1.aenc1Name, "wmaenc1" },
		{ "wmaenc1", "seconds", DVEVM_ST_INT, &(G->wmaenc1.seconds), (void *) DEFAULT_AACHEENC1_TIME },
		{ "wmaenc1", "sampleRate", DVEVM_ST_INT, &(G->wmaenc1.aenc1Params.audenc_params.sampleRate), (void *) 44100 },
		{ "wmaenc1", "bitRate", DVEVM_ST_INT, &(G->wmaenc1.aenc1Params.audenc_params.bitRate), (void *) 96000 },
		{ "wmaenc1", "channelMode", DVEVM_ST_INT, &(G->wmaenc1.aenc1Params.audenc_params.channelMode), (void *) (XDAS_Int32)(IAUDIO_2_0) },
		{ "wmaenc1", "dataEndianness", DVEVM_ST_INT, &(G->wmaenc1.aenc1Params.audenc_params.dataEndianness), (void *) (XDAS_Int32)(XDM_LE_16) },
		{ "wmaenc1", "encMode", DVEVM_ST_INT, &(G->wmaenc1.aenc1Params.audenc_params.encMode), (void *) (XDAS_Int32)(IAUDIO_CBR) },
		{ "wmaenc1", "inputFormat", DVEVM_ST_INT, &(G->wmaenc1.aenc1Params.audenc_params.inputFormat), (void *) (XDAS_Int32)(IAUDIO_INTERLEAVED) },
		{ "wmaenc1", "inputBitsPerSample", DVEVM_ST_INT, &(G->wmaenc1.aenc1Params.audenc_params.inputBitsPerSample), (void *) 16 },
		{ "wmaenc1", "maxBitRate", DVEVM_ST_INT, &(G->wmaenc1.aenc1Params.audenc_params.maxBitRate), (void *) 192000 },
		{ "wmaenc1", "dualMonoMode", DVEVM_ST_INT, &(G->wmaenc1.aenc1Params.audenc_params.dualMonoMode), (void *) (XDAS_Int32) IAUDIO_DUALMONO_LR },
		{ "wmaenc1", "crcFlag", DVEVM_ST_INT, &(G->wmaenc1.aenc1Params.audenc_params.crcFlag), (void *) XDAS_FALSE },
		{ "wmaenc1", "ancFlag", DVEVM_ST_INT, &(G->wmaenc1.aenc1Params.audenc_params.ancFlag), (void *) XDAS_FALSE },
		{ "wmaenc1", "lfeFlag", DVEVM_ST_INT, &(G->wmaenc1.aenc1Params.audenc_params.lfeFlag), (void *) XDAS_FALSE },
		{ "wmaenc1", "iBitRate_var", DVEVM_ST_INT, &(G->wmaenc1.aenc1Params.iBitRate_var), (void *) 0 },
		{ "wmaenc1", "dynamicparams.sampleRate", DVEVM_ST_INT, &(G->wmaenc1.aenc1DynParams.audenc_dynamicparams.sampleRate), (void *) 44100 },
		{ "wmaenc1", "dynamicparams.bitRate", DVEVM_ST_INT, &(G->wmaenc1.aenc1DynParams.audenc_dynamicparams.bitRate), (void *) 96000 },
		{ "wmaenc1", "dynamicparams.channelMode", DVEVM_ST_INT, &(G->wmaenc1.aenc1DynParams.audenc_dynamicparams.channelMode), (void *) IAUDIO_2_0 },
		{ "wmaenc1", "dynamicparams.lfeFlag", DVEVM_ST_INT, &(G->wmaenc1.aenc1DynParams.audenc_dynamicparams.lfeFlag), (void *) XDAS_FALSE },
		{ "wmaenc1", "dynamicparams.dualMonoMode", DVEVM_ST_INT, &(G->wmaenc1.aenc1DynParams.audenc_dynamicparams.dualMonoMode), (void *) IAUDIO_DUALMONO_LR },
		{ "wmaenc1", "dynamicparams.inputBitsPerSample", DVEVM_ST_INT, &(G->wmaenc1.aenc1DynParams.audenc_dynamicparams.inputBitsPerSample), (void *) 16 },


	};

		DVEVM_CODEC_NUM = sizeof(dvevmStMapArr) / sizeof(DvevmStMapTable);
		MAP = (DvevmStMapTable *) calloc(DVEVM_CODEC_NUM, sizeof(DvevmStMapTable));

		if (MAP != NULL)
		{
			memcpy(MAP, dvevmStMapArr, DVEVM_CODEC_NUM * sizeof(DvevmStMapTable));
			valInitialized = DVEVM_ST_TRUE;
		}
	}
}
