#############################################################
# Makefile for NAND_ECC_Test program for the DM355.         #
#############################################################
# Auth: Daniel Allred
# Vers: v1.00 on 19-Mar-2008
#	    
PROGRAM:=NAND_ECC_Test
DEVSTRING:=DM35x

PROJECTFILE=$(PROGRAM).pjt
EXECUTABLE=./Debug/$(PROGRAM).out


# Target definitions
.PHONY : all clean
all: 
		timake $(PROJECTFILE) Debug

clean:
		timake $(PROJECTFILE) Debug -clean



