#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#

unexport MAKEFILE_LIST
override PKGDIR = ittiam/app/g711_dec_app
XDCINCS = -I. -I$(strip $(subst ;, -I,$(subst $(space),\$(space),$(XPKGPATH))))
XDCPKGS = $(call pkgsearch,xdc )
XDCINCS += $(if $(XDCPKGS),-I$(subst $(space), -I,$(XDCPKGS)))
IMPORTPATH += $(if $(XDCPKGS),;$(subst $(space),;,$(XDCPKGS)))
XDCCFGDIR = package/cfg/

#
# The following dependencies ensure package.mak is rebuilt
# in the event that some included BOM script changes.
#
ifneq (clean,$(MAKECMDGOALS))
/home/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/gnu/targets/UCArm9.xs:
package.mak: /home/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/gnu/targets/UCArm9.xs
/home/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/ti/targets/MSP430.xs:
package.mak: /home/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/ti/targets/MSP430.xs
/home/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/gnu/targets/ITarget.xs:
package.mak: /home/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/gnu/targets/ITarget.xs
/home/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/gnu/targets/arm/GCArmv7A.xs:
package.mak: /home/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/gnu/targets/arm/GCArmv7A.xs
/home/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/bld/_gen.xs:
package.mak: /home/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/bld/_gen.xs
/home/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/include/utils.tci:
package.mak: /home/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/include/utils.tci
/home/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/bld/Executable.xs:
package.mak: /home/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/bld/Executable.xs
/home/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/bld/ITargetFilter.xs:
package.mak: /home/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/bld/ITargetFilter.xs
/home/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/gnu/targets/Linux86.xs:
package.mak: /home/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/gnu/targets/Linux86.xs
/home/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/gnu/targets/Mingw.xs:
package.mak: /home/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/gnu/targets/Mingw.xs
/home/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/xmlgen.xs:
package.mak: /home/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/xmlgen.xs
/home/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/package.xs:
package.mak: /home/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/package.xs
/home/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/gnu/targets/MVArm9.xs:
package.mak: /home/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/gnu/targets/MVArm9.xs
/home/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/template.xs:
package.mak: /home/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/template.xs
/home/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/bld/Utils.xs:
package.mak: /home/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/bld/Utils.xs
/home/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/ti/targets/package.xs:
package.mak: /home/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/ti/targets/package.xs
/home/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/bld/package.xs:
package.mak: /home/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/bld/package.xs
/home/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/gnu/targets/package.xs:
package.mak: /home/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/gnu/targets/package.xs
/home/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/bld/Library.xs:
package.mak: /home/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/bld/Library.xs
/home/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/IPackage.xs:
package.mak: /home/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/IPackage.xs
package.mak: package.bld
/home/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/xmlgen2.xs:
package.mak: /home/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/xmlgen2.xs
/home/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/xdc.tci:
package.mak: /home/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/xdc.tci
/home/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/services/global/Clock.xs:
package.mak: /home/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/services/global/Clock.xs
/home/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/gnu/targets/arm/GCArmv6.xs:
package.mak: /home/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/gnu/targets/arm/GCArmv6.xs
/home/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/om2.xs:
package.mak: /home/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/om2.xs
/home/ITTIAM/100200/audio_speech/release_process/release_out/g711_dec_2_0_00_production_dm365_mvl/packages-production/user.bld:
package.mak: /home/ITTIAM/100200/audio_speech/release_process/release_out/g711_dec_2_0_00_production_dm365_mvl/packages-production/user.bld
/home/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/bld/BuildEnvironment.xs:
package.mak: /home/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/bld/BuildEnvironment.xs
/home/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/bld/PackageContents.xs:
package.mak: /home/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/bld/PackageContents.xs
/home/ITTIAM/100200/audio_speech/release_process/release_out/g711_dec_2_0_00_production_dm365_mvl/packages-production/config.bld:
package.mak: /home/ITTIAM/100200/audio_speech/release_process/release_out/g711_dec_2_0_00_production_dm365_mvl/packages-production/config.bld
/home/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/services/global/Trace.xs:
package.mak: /home/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/services/global/Trace.xs
/home/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/bld/Script.xs:
package.mak: /home/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/bld/Script.xs
/home/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/bld/Repository.xs:
package.mak: /home/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/bld/Repository.xs
/home/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/ti/targets/ITarget.xs:
package.mak: /home/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/ti/targets/ITarget.xs
/home/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/bld/ITarget.xs:
package.mak: /home/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/xdc/bld/ITarget.xs
endif

gnu.targets.MVArm9.rootDir ?= /home/dm365/mv_pro_5_0/montavista/pro/devkit/arm/v5t_le
gnu.targets.packageBase ?= /home/dm365/dvsdk_2_10_01_18/xdctools_3_15_01_59/packages/gnu/targets/
.PRECIOUS: $(XDCCFGDIR)/%.o470MV
.PHONY: all,470MV .dlls,470MV .executables,470MV test,470MV
all,470MV: .executables,470MV
.executables,470MV: .libraries,470MV
.executables,470MV: .dlls,470MV
.dlls,470MV: .libraries,470MV
.libraries,470MV: .interfaces
	@$(RM) $@
	@$(TOUCH) "$@"

.help::
	@$(ECHO) xdc test,470MV
	@$(ECHO) xdc .executables,470MV
	@$(ECHO) xdc .libraries,470MV
	@$(ECHO) xdc .dlls,470MV


all: .executables 
.executables: .libraries .dlls
.libraries: .interfaces

PKGCFGS := $(wildcard package.xs) package/build.cfg
.interfaces: package/package.xdc.inc package/package.defs.h package.xdc $(PKGCFGS)

-include package/package.xdc.dep
package/%.xdc.inc package/%_ittiam.app.g711_dec_app.c package/%.defs.h: %.xdc $(PKGCFGS)
	@$(MSG) generating interfaces for package ittiam.app.g711_dec_app" (because $@ is older than $(firstword $?))" ...
	$(XSRUN) -f xdc/services/intern/cmd/build.xs $(MK_IDLOPTS) -m package/package.xdc.dep -i package/package.xdc.inc package.xdc

.executables,470MV .executables: g711_dec_app.x470MV

-include package/cfg/g711_dec_app_x470MV.mak
ifneq (clean,$(MAKECMDGOALS))
-include package/cfg/g711_dec_app_x470MV.dep
endif
package/cfg/g711_dec_app/app.o470MV package/cfg/g711_dec_app/arm9e_linux_test_utility.o470MV package/cfg/g711_dec_app_x470MV.o470MV package/cfg/g711_dec_app/ceapp.o470MV : | package/cfg/g711_dec_app_x470MV.xdl
g711_dec_app.x470MV:
	$(RM) $@
	@$(MSG) lnk470MV $@ ...
	$(gnu.targets.MVArm9.rootDir)/bin/arm_v5t_le-gcc   -UGT -lpthread -o $@ package/cfg/g711_dec_app/app.o470MV package/cfg/g711_dec_app/arm9e_linux_test_utility.o470MV package/cfg/g711_dec_app_x470MV.o470MV package/cfg/g711_dec_app/ceapp.o470MV  package/cfg/g711_dec_app_x470MV.xdl  -lstdc++ -L$(gnu.targets.MVArm9.rootDir)/armv5tl-montavista-linux-gnueabi/lib
	
g711_dec_app.x470MV:LD_LIBRARY_PATH=


ifeq (,$(wildcard .libraries,470MV))
g711_dec_app.x470MV package/cfg/g711_dec_app_x470MV.c: .libraries,470MV
endif

package/cfg/g711_dec_app_x470MV.c package/cfg/g711_dec_app_x470MV.h package/cfg/g711_dec_app_x470MV.xdl: override _PROG_NAME := g711_dec_app.x470MV
package/cfg/g711_dec_app_x470MV.c: package/cfg/g711_dec_app_x470MV.cfg
g711_dec_app.test test,470MV test: g711_dec_app.x470MV.test

g711_dec_app.x470MV.test:: g711_dec_app.x470MV
ifeq (,$(_TESTLEVEL))
	@$(MAKE) -R -r --no-print-directory -f $(XDCROOT)/packages/xdc/bld/xdc.mak _TESTLEVEL=1 g711_dec_app.x470MV.test
else
	@$(MSG) running $<  ...
	$(call EXEC.g711_dec_app.x470MV, ) 
endif


clean:: clean,470MV
	-$(RM) package/cfg/g711_dec_app_x470MV.cfg
	-$(RM) package/cfg/g711_dec_app_x470MV.dep
	-$(RM) package/cfg/g711_dec_app_x470MV.c
	-$(RM) package/cfg/g711_dec_app_x470MV.xdc.inc

clean,470MV::
	-$(RM) g711_dec_app.x470MV
	-$(RM) .tmp,g711_dec_app.x470MV,*

%,copy:
	@$(if $<,,$(MSG) don\'t know how to build $*; exit 1)
	@$(MSG) cp $< $@
	$(RM) $@
	$(CP) $< $@
ceapp.o470MV,copy : package/cfg/g711_dec_app/ceapp.o470MV
g711_dec_app_x470MV.s470MV,copy : package/cfg/g711_dec_app_x470MV.s470MV
arm9e_linux_test_utility.o470MV,copy : package/cfg/g711_dec_app/arm9e_linux_test_utility.o470MV
ceapp.s470MV,copy : package/cfg/g711_dec_app/ceapp.s470MV
app.o470MV,copy : package/cfg/g711_dec_app/app.o470MV
arm9e_linux_test_utility.s470MV,copy : package/cfg/g711_dec_app/arm9e_linux_test_utility.s470MV
g711_dec_app_x470MV.o470MV,copy : package/cfg/g711_dec_app_x470MV.o470MV
app.s470MV,copy : package/cfg/g711_dec_app/app.s470MV

$(XDCCFGDIR)%.c $(XDCCFGDIR)%.h $(XDCCFGDIR)%.xdl: $(XDCCFGDIR)%.cfg .interfaces $(XDCROOT)/packages/xdc/cfg/Main.xs
	@$(MSG) "configuring $(_PROG_NAME) from $< ..."
	$(CONFIG) $(_PROG_XSOPTS) xdc.cfg $(_PROG_NAME) $(XDCCFGDIR)$*.cfg $(XDCCFGDIR)$*

.PHONY: release,ittiam_app_g711_dec_app
ittiam_app_g711_dec_app.tar: package.bld
ittiam_app_g711_dec_app.tar: g711_dec_app.cfg
ittiam_app_g711_dec_app.tar: g711_dec_app.x470MV
ittiam_app_g711_dec_app.tar: package/package.xdc.inc
ittiam_app_g711_dec_app.tar: package/package.rel.dot
ittiam_app_g711_dec_app.tar: package.xdc
ittiam_app_g711_dec_app.tar: package/package.bld.xml
ittiam_app_g711_dec_app.tar: app.c
ittiam_app_g711_dec_app.tar: ig711dec.h
ittiam_app_g711_dec_app.tar: arm9e_linux_test_utility.c
ittiam_app_g711_dec_app.tar: package/package.ext.xml
ittiam_app_g711_dec_app.tar: ceapp.c
ittiam_app_g711_dec_app.tar: package/build.cfg
ittiam_app_g711_dec_app.tar: g711dec_ittiam.h
ittiam_app_g711_dec_app.tar: test_utility.h
ifneq (clean,$(MAKECMDGOALS))
-include package/rel/ittiam_app_g711_dec_app.tar.dep
endif
package/rel/ittiam_app_g711_dec_app/ittiam/app/g711_dec_app/package/package.rel.xml:

ittiam_app_g711_dec_app.tar: package/rel/ittiam_app_g711_dec_app.xdc.inc package/rel/ittiam_app_g711_dec_app/ittiam/app/g711_dec_app/package/package.rel.xml
	@$(MSG) making release file $@ "(because of $(firstword $?))" ...
	-$(RM) $@
	$(call MKRELTAR,package/rel/ittiam_app_g711_dec_app.xdc.inc,package/rel/ittiam_app_g711_dec_app.tar.dep)


release release,ittiam_app_g711_dec_app: all ittiam_app_g711_dec_app.tar
clean:: .clean
	-$(RM) ittiam_app_g711_dec_app.tar
	-$(RM) package/rel/ittiam_app_g711_dec_app.xdc.inc
	-$(RM) package/rel/ittiam_app_g711_dec_app.tar.dep

clean:: .clean
	-$(RM) .libraries .libraries,*
clean:: 
	-$(RM) .dlls .dlls,*
#
# The following clean rule removes user specified
# generated files or directories.
#

ifneq (clean,$(MAKECMDGOALS))
ifeq (,$(wildcard package))
    $(shell $(MKDIR) package)
endif
ifeq (,$(wildcard package/external))
    $(shell $(MKDIR) package/external)
endif
ifeq (,$(wildcard package/cfg))
    $(shell $(MKDIR) package/cfg)
endif
ifeq (,$(wildcard package/cfg/g711_dec_app))
    $(shell $(MKDIR) package/cfg/g711_dec_app)
endif
ifeq (,$(wildcard package/lib))
    $(shell $(MKDIR) package/lib)
endif
ifeq (,$(wildcard package/rel))
    $(shell $(MKDIR) package/rel)
endif
ifeq (,$(wildcard package/internal))
    $(shell $(MKDIR) package/internal)
endif
endif
clean::
	-$(RMDIR) package


