#! /bin/sh

matrixgui="/usr/bin/matrix_guiE"
GUI_OPTS="-qws -display transformed:Rot0 -geometry 720x480-8+8 /usr/share/matrix/html/menu_main.html"
PIDFILE="/var/run/matrix-gui-e.pid"

test -x "$matrixgui" || exit 0

case "$1" in
  start)
    chvt 4
    if [ -e $PIDFILE ]; then
      PIDDIR=/proc/$(cat $PIDFILE)
      if [ -d ${PIDDIR} -a  "$(readlink -f ${PIDDIR}/exe)" = "${matrixgui}" ]; then
        echo "$DESC already started; not starting."
      else
        echo "Removing stale PID file $PIDFILE."
        rm -f $PIDFILE
      fi
    fi
    echo -n "Starting Matrix GUI application"
    echo COMPONENT > /sys/class/davinci_display/ch0/output
    echo 480P-60 > /sys/class/davinci_display/ch0/mode
    start-stop-daemon --start --quiet --background --pidfile /var/run/matrix-gui-e.pid --exec $matrixgui -- $GUI_OPTS
    echo "."
	pidof matrix_guiE > $PIDFILE
    ;;
  stop)
    echo -n "Stopping Matrix GUI application"
    start-stop-daemon --stop --quiet --pidfile /var/run/matrix-gui-e.pid
    echo "."
    ;;
  *)
    echo "Usage: /etc/init.d/matrix-gui-e {start|stop}"
    exit 1
esac

exit 0
