/*   Do *not* directly modify this file.  It was    */
/*   generated by the Configuration Tool; any  */
/*   changes risk being overwritten.                */

/* INPUT fastcopytest_lld_dm6467_x64P.cdb */

/*  Include Header File  */
#include "fastcopytest_lld_dm6467_x64Pcfg.h"

/*  Config Structures */
/*  Handles  */
