/****************************************************************
 *  TI C642x AIS Utilities                                      *
 ****************************************************************/
 
This directory contains the source for the HexAIS and GenAIS utilities
for the C642x device family. The HexAIS utility is intended to produce
a hex file that can be used with the FlashBurn GUI utility.  The GenAIS
file is intended to produce a binary AIS file for the EMIFA FASTBOOT 
boot mode.  This binary AIS file can be written to the NOR flash using the
C642x_NORWriter CCS project.  The binary AIS could also be processed by 
the HexAIS utility using the '-ais2hex' option, though it will produce the
same output as would be produced by using the '-coff2hex' option on the
original .out file.
 
Running
=======

--- Under Windows ---
This applications can be run from the commandline under Windows with 
the .Net Framework 2.0 or later installed.  

  HexAIS.exe [options] <input file name>
  GenAIS.exe [options] <input file name>
	
--- Under Linux ---
It can also be run on a Linux machine with the latest open-source Mono
Framework installed.

  mono HexAIS.exe [options] <input file name>
  mono GenAIS.exe [options] <input file name>    

    
Options
=======

For the HexAIS utility, the available options include:
 -h                      Show the help screen.
 -o <Output File Name>   Explicitly specify the output filename.
                         Default is input file name with .hex extension.
 -coff2hex               Process the input file as a valid COFF file, internally generate the
                         AIS format, then convert to hex output (requires C642x.ini file).
 -ais2hex                Process the input file as a valid binary AIS file
                         and convert to hex output. AIS file should be emifa
                         boot mode, generated by genAIS perl script.
                         
For the GenAIS utility, the available options include:
 -h                      Show the help screen.
 -o <Output File Name>   Explicitly specify the output filename.
                         Default is input file name with .hex extension.                         


Compiling
=========

A makefile is included for compiling the utilities.  The make command should
be run from the top-level directory (the one containing the 'HexAIS', 'GenAIS', and
'AISextra' directories). The AISextra obj file is generated first.
This COFF object file is used by the HexAIS application when the -coff2hex option
is supplied and also by the GenAIS application. It is included in the generated AIS
image to assist in application boot (specifically turning on the power domains 
specified in the ini file).


- Under Windows - 
The currently supported method is to use the Cygwin enviroment (such as
the one provided with the Montavista Linux tools for Windows) and put the 
C sharp compiler's (the csc.exe executable) install location in the user's
path.  This compiler comes with the .NET Framework installation and can
usually be found in C:\WINDOWS\Microsoft.NET\Framework\<version number>.

In addition, the location of the C6000 Codegen tools should be in the 
path (usually something like C:\CCStudio_v3.3\C6000\cgtools\bin).

Then go to the top level directory of the package and run:
	
	make

- Under Linux -
The Mono Framework must be installed and in the path.  RPMs are available 
at 'http://www.mono-project.com/Downloads'.  

In addition, the location of the C6000 Codegen tools should be in the 
path.

Then go to the top level directory of the package and run:

	make

