/*
 *  Copyright 2010 by Texas Instruments Incorporated.
 *
 */

/* this file was generated by xdc/bld/stddefs.xdt */
/*
 *  @(#) gnu.targets; 1, 0, 1,387; 2-24-2010 16:24:00; /db/ztree/library/trees/xdctargets/xdctargets-b36x/src/
 */

