/*
 *  Copyright 2010 by Texas Instruments Incorporated.
 *
 */

/* this file was generated by xdc/bld/stddefs.xdt */
/*
 *  @(#) microsoft.targets; 1, 0, 2, 0,387; 2-24-2010 16:24:01; /db/ztree/library/trees/xdctargets/xdctargets-b36x/src/
 */

