#############################################################
# Makefile for NANDWriter program for the DM355.            #
#############################################################
# Auth: Daniel Allred
#
PROGRAM:=NORWriter

PROJECTFILE=$(PROGRAM).pjt
EXECUTABLE=./Debug/$(PROGRAM).out


# Target definitions
.PHONY : all clean
all: 
		timake $(PROJECTFILE) Debug

clean:
		timake $(PROJECTFILE) Debug -clean



