#############################################################
# Makefile for DM644x_NANDWriter program for the DM644x     #
#############################################################
# Auth: Daniel Allred
#	    
PROGRAM:=NANDWriter

PROJECTFILE=$(PROGRAM).pjt
EXECUTABLE=./Debug/$(PROGRAM).out


# Target definitions
.PHONY : all clean
all: 
		timake $(PROJECTFILE) Debug

clean:
		timake $(PROJECTFILE) Debug -clean



